// Offline canonical prefix table generator. No allocation/table setup on ESP8266.
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../..');
const dir = path.join(root, 'yoRadio/src/audioI2S/aac_decoder');
const source = fs.readFileSync(path.join(dir, 'aac_decoder.cpp'), 'utf8')
  .replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '');
function body(name) {
  const match = source.match(new RegExp('const [^;=]+\\b' + name + '(?:\\[[^\\]]*\\])?\\s+PROGMEM\\s*=\\s*([\\s\\S]*?);'));
  assert.ok(match, name);
  return match[1];
}
const numbers = text => [...text.matchAll(/-?0x[0-9a-f]+|-?\d+/gi)].map(m => Number(m[0]));
function infos(name) {
  return [...body(name).matchAll(/\{\s*(\d+)\s*,\s*\{([^}]+)\}\s*,\s*(\d+)\s*\}/g)]
    .map(m => ({max: +m[1], count: numbers(m[2]), offset: +m[3]}));
}
const spectral = numbers(body('huffTabSpec'));
const scale = numbers(body('huffTabScaleFact'));
const books = [...infos('huffTabSpecInfo').map(info => ({info, values:spectral})),
  ...infos('huffTabScaleFactInfo').map(info => ({info, values:scale}))];
assert.equal(books.length, 12);
const lines = ['// Generated by tools/esp8266_audio_profile/generate_aac_prefix.js; do not edit.',
  '// Packed canonical symbol (signed low 16 bits) and code length (high 16).',
  '// Zero entry uses the exact canonical fallback. Flash only; no pointer table.',
  'static const uint32_t aacHuffmanPrefix[12][256] PROGMEM = {'];
for (const {info, values} of books) {
  const table = Array(256).fill(0);
  let code = 0, symbol = info.offset;
  for (let bits = 1; bits <= info.max; ++bits) {
    const count = info.count[bits - 1];
    for (let i = 0; i < count; ++i) {
      if (bits <= 8) {
        const entry = (bits << 16) | (values[symbol + i] & 0xffff);
        const start = (code + i) << (8 - bits);
        for (let p = start; p < start + (1 << (8 - bits)); ++p) {
          assert.equal(table[p], 0);
          table[p] = entry;
        }
      }
    }
    symbol += count;
    code = (code + count) * 2;
  }
  assert.equal(code, 2 ** (info.max + 1));
  lines.push('    {');
  for (let p = 0; p < table.length; p += 8)
    lines.push('        ' + table.slice(p, p + 8).map(x => '0x' + x.toString(16).padStart(8, '0')).join(', ') + ',');
  lines.push('    },');
}
lines.push('};', '');
const result = lines.join('\n');
const target = path.join(dir, 'aac_huffman_prefix.inc');
if (process.argv.includes('--check')) assert.equal(fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n'), result);
else fs.writeFileSync(target, result);
console.log('AAC prefix table: 12 codebooks, 12288 flash bytes, zero runtime RAM');
