#ifndef optionschecker_h
#define optionschecker_h

#if REAL_LEDBUILTIN==TFT_RST
#  error LED_BUILTIN IS THE SAME AS TFT_RST. Check it in myoptions.h
#endif

#if REAL_LEDBUILTIN==VS1053_RST
#  error LED_BUILTIN IS THE SAME AS VS1053_RST. Check it in myoptions.h
#endif

#if (I2S_DOUT!=255) && (VS1053_CS!=255)
#  error YOU MUST CHOOSE BETWEEN I2S DAC AND VS1053 BY DISABLING THE SECOND MODULE IN THE myoptions.h
#endif

#if I2S_INTERNAL_OUTPUT != AUDIO_OUTPUT_DAC && I2S_INTERNAL_OUTPUT != AUDIO_OUTPUT_PDM
#  error I2S_INTERNAL_OUTPUT MUST BE AUDIO_OUTPUT_DAC OR AUDIO_OUTPUT_PDM
#endif

#if I2S_INTERNAL_OUTPUT == AUDIO_OUTPUT_PDM && !I2S_INTERNAL
#  error AUDIO_OUTPUT_PDM REQUIRES I2S_INTERNAL=true
#endif

#if !(defined(ARDUINO_ESP32_DEV) || defined(ARDUINO_ESP32S3_DEV) || defined(ARDUINO_ESP32C3_DEV))
#  error ONLY MODULES "ESP32 Dev Module", "ESP32 Wrover Module" AND "ESP32 S3 Dev Module" ARE SUPPORTED. PLEASE SELECT ONE OF THEM IN THE MENU >> TOOLS >> BOARD
#endif

#endif


