const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const f=require('../tools/esp8266_opus_asm/mdct_post_pair.cjs'),sem=require('../tools/esp8266_opus_asm/mdct_post_proof.cjs'),base=require('../tools/esp8266_opus_asm/frozen_reloads.cjs'),report=require('../tools/esp8266_opus_asm/report_mdct_post_pair.cjs'),{hash}=require('../tools/esp8266_opus_asm/export.cjs');
const proof=f.read(path.join(f.art('candidate'),'preflight.json')),p=proof.patches[0],old=proof.functions[f.names[0]].disassembly,now=proof.actual_functions[f.names[0]].disassembly;
test('all225 post-rotation pairs preserve arbitrary PCM32 and exact in-place events',()=>{assert.deepEqual(sem.prove(old,now,p,proof.tables),proof.symbolic);assert.equal(proof.symbolic.pairs,225);assert.deepEqual(proof.symbolic.table_loads_per_pair,{old:8,new:4});
 for(const[a,b]of[['srai\ta13, a13, 15','srai\ta13, a13, 14'],['srai\ta4, a12, 16','srai\ta4, a14, 16'],['addi\ta2, a2, -2','addi\ta2, a2, -4'],['s32i.n\ta7, a8, 4','s32i.n\ta7, a8, 0']]){const bad=now.replace(a,b);assert.notEqual(bad,now);assert.throws(()=>sem.prove(old,bad,p,proof.tables));}});
test('rear reads must precede front stores; reordered events fail even if disjoint fixtures match values',()=>{const rows=base.rows(now),read=rows.find(r=>r.text==='l32i a3, a8, 0'),write=rows.find(r=>r.text==='s32i a10, a15, 0');assert.equal(read.bytes,write.bytes);const modified=now.split('\n').map(l=>{if(l.startsWith(read.address.toString(16)+':'))return read.address.toString(16)+': 0000 s32i.n a10, a15, 0';if(l.startsWith(write.address.toString(16)+':'))return write.address.toString(16)+': 0000 l32i.n a3, a8, 0';return l;}).join('\n');assert.notEqual(now,modified);assert.throws(()=>sem.prove(old,modified,p,proof.tables),/event/);});
test('phase, invariant stack and exit scratch liveness are fail-closed',()=>{for(const[a,b]of[['bbsi\ta9, 1,','bbsi\ta9, 2,'],['addi.n\ta9, a9, 2','addi.n\ta9, a9, 4'],['l32i.n\ta7, a1, 8','l32i.n\ta7, a1, 12']]){const bad=now.replace(a,b);assert.notEqual(now,bad);assert.throws(()=>sem.prove(old,bad,p,proof.tables));}
 assert.deepEqual(sem.exitLiveness(now,p),proof.symbolic.liveness);const bad=now.split('\n').map(l=>l.startsWith('4024734e:')?l.replace('a8, a1, 36','a8, a12, 36'):l).join('\n');assert.notEqual(now,bad);assert.throws(()=>sem.exitLiveness(bad,p),/scratch/);});
test('numeric complete transforms preserve central in-place pair across all standard N4 and PCM32 edges',()=>{const elf=zlib.gunzipSync(fs.readFileSync(path.join(f.art('candidate'),'parent.elf.gz'))),{wordOffset}=require('../tools/esp8266_opus_asm/frozen_div.cjs');let seed=7349,cases=0;const random=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return seed>>>0;},edge=[0,1,0xffffffff,0x7fffffff,0x80000000,32767,32768,65535,0xffff0000,0x40000001];const select=s=>base.rows(s).filter(r=>r.address>=p.address&&r.address<p.address+p.bytes);
 for(const t of proof.tables.supported_standard_transforms)for(const offset of[0,4,64,132]){const x=sem.fixture(t,0,t.n/2,false,0x3ffe1000+offset);for(let i=0;i<t.n*2;i++)x.memory.set(x.baseAddress+i*4,i<edge.length?edge[i]:random());for(let i=0;i<t.n*4;i+=4)x.memory.set(t.t0+i,elf.readUInt32LE(wordOffset(elf,t.t0+i)));
  const a=sem.interpret(select(old),p,x.regs,x.memory,t.n/2),b=sem.interpret(select(now),p,x.regs,x.memory,t.n/2),events=v=>v.events.filter(e=>e.address<0x40200000&&![x.sp+8,x.sp+12,x.sp+16].includes(e.address));assert.deepEqual(events(a),events(b));for(const r of['a1','a9','a15'])assert.equal(a.state[r],b.state[r]);cases++;}assert.equal(cases,16);});
test('one276-byte patch preserves all other ELF/app bytes, table data, frame/RAM and settings',()=>{const{manifests}=report.verifyPair(),a=zlib.gunzipSync(fs.readFileSync(path.join(f.art('candidate'),'parent.elf.gz')));assert.equal(hash(base.patchElf(a,[p])),proof.candidate_elf_sha256);assert.equal(p.bytes,276);assert.equal(proof.static_ram_delta,0);assert.equal(proof.stack_delta,0);
 for(const mutate of[m=>m.cpu_mhz=80,m=>m.flash='QIO80',m=>m.opus_benchmark_output=true,m=>m.opus_function_profile=true,m=>m.post_link_three_pair_variant='control']){const b=structuredClone(manifests.candidate);mutate(b);assert.throws(()=>f.manifestPair(manifests.control,b));}
 const bad=structuredClone(proof.tables);bad.supported_standard_transforms[3].n=59;assert.throws(()=>sem.prove(old,now,p,bad));});
