const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { root } = require('../tools/esp8266_opus_profile/build_host.cjs');
const { sha256, inspectPackets } = require('../tools/esp8266_opus_profile/fixtures.cjs');
const { directory, repacketize } = require('../tools/esp8266_opus_profile/generate_phase_fixtures.cjs');
const { runPhaseRegressions } = require('../tools/esp8266_opus_profile/run_phase_regressions.cjs');

test('phase corpus pins short CELT frames, all packet layouts and mono fallback', () => {
  const manifest = JSON.parse(fs.readFileSync(path.join(directory, 'manifest.json'), 'utf8'));
  assert.equal(manifest.fixtures.length, 10);
  const durations = new Set(), codes = new Set(), channels = new Set();
  for (const fixture of manifest.fixtures) {
    const data = fs.readFileSync(path.join(directory, fixture.name + '.opuspkt'));
    assert.equal(sha256(data), fixture.opuspkt_sha256);
    const actual = inspectPackets(data);
    for (const [key, value] of Object.entries(actual)) assert.deepEqual(value, fixture[key]);
    assert.equal(actual.modes.CELT, actual.packets);
    for (const duration of Object.keys(actual.packet_durations_ms)) durations.add(Number(duration));
    for (const channel of Object.keys(actual.packet_channels)) channels.add(Number(channel));
    for (let offset = 0; offset < data.length;) {
      codes.add(data[offset + 2] & 3);
      offset += 2 + data.readUInt16LE(offset);
    }
  }
  assert.deepEqual([...durations].sort((a, b) => a - b), [2.5, 5, 10, 20]);
  assert.deepEqual([...codes].sort(), [0, 1, 2, 3]);
  assert.deepEqual([...channels].sort(), [1, 2]);
});

test('phase repacketizer encodes CBR/VBR layouts without changing frame bodies', () => {
  const a = Buffer.from([0x94, 11, 22]), b = Buffer.from([0x94, 33, 44]);
  assert.deepEqual(repacketize([a, b], 2), [Buffer.from([0x95, 11, 22, 33, 44])]);
  assert.deepEqual(repacketize([a, b], 2, true), [Buffer.from([0x96, 2, 11, 22, 33, 44])]);
  const large = Buffer.concat([Buffer.from([0x94]), Buffer.alloc(307, 0x33)]);
  assert.deepEqual(repacketize([large, b], 2, true)[0].subarray(0, 3), Buffer.from([0x96, 255, 13]));
  assert.deepEqual(repacketize([a, b, a, b], 4)[0], Buffer.from([0x97, 4, 11, 22, 33, 44, 11, 22, 33, 44]));
  assert.throws(() => repacketize([a, Buffer.from([0x84, 33, 44])], 2), /different Opus configurations/);
  assert.throws(() => repacketize([a, large], 2));
});

test('saved phase evidence is exact with real 6144-byte capacity and exercised guards', () => {
  const report = JSON.parse(fs.readFileSync(path.join(root, 'tools/esp8266_opus_profile/pcm-scratch-results.json'), 'utf8'));
  assert.equal(report.passed, true);
  assert.equal(report.arithmetic, 'OPUS_FAST_INT64=0');
  assert.deepEqual(report.pristine_provenance.changed_files, ['celt/arch.h']);
  for (const [file, expected] of Object.entries(report.phase_source_sha256_lf))
    assert.equal(sha256(Buffer.from(fs.readFileSync(path.join(root, file), 'utf8').replace(/\r\n/g, '\n'))), expected, 'rerun evidence after changing ' + file);
  assert.equal(report.cases.length, 22);
  assert.ok(report.coverage.borrowed_by_lm.every(count => count > 0));
  assert.ok(report.coverage.transient_borrowed > 0);
  assert.ok(report.coverage.dual_stereo_borrowed > 0);
  assert.ok(report.coverage.borrow_denied > 0);
  for (const result of report.cases) {
    assert.equal(result.pcm.exact, true, result.name);
    assert.equal(result.pcm.mismatched_samples, 0);
    assert.equal(result.pcm.snr_db, 'Infinity');
    assert.equal(result.pcm.reference_pcm_sha256, result.pcm.actual_pcm_sha256);
    assert.equal(result.pristine.reset_exact, true);
    assert.equal(result.bounded.reset_exact, true);
    assert.equal(result.bounded.pcm_guards_ok, true);
    assert.equal(result.bounded.scratch_byte_capacity_bytes, 6144);
    assert.ok(result.bounded.scratch_byte_peak_bytes <= 6144);
    assert.ok(result.bounded.scratch_word_peak_bytes <= 16384);
    if (result.name.startsWith('downsample-')) assert.deepEqual(result.bounded.borrowed_by_lm, [0, 0, 0, 0]);
    result.route.forEach((file, i) => {
      // The synthetic SILK stereo route is regenerated by the standard runner.
      // Its hash is also recorded by the independently checked standard evidence.
      if (!file.startsWith('.build/')) assert.equal(sha256(fs.readFileSync(path.join(root, file))), result.input_sha256[i]);
    });
  }
  assert.equal(report.cases.find(result => result.name === 'standard-mixed-plc').bounded.scratch_byte_peak_bytes, 5968);
  assert.equal(report.cases.find(result => result.name === 'standard-burst-plc').bounded.plc_frames, 210);
  assert.equal(report.cases.find(result => result.name === 'mono-20ms').bounded.borrowed_by_lm.reduce((a, b) => a + b), 0);
  assert.equal(report.standard_regression.passed, true);
  for (const result of report.standard_regression.fixtures) {
    assert.equal(result.pcm.exact, true);
    assert.equal(result.bounded.oom_reinitialized_exact, true);
    assert.equal(result.bounded.arena_guards_ok, true);
  }
});

test('real phase decoders reproduce the complete reduced-scratch evidence', {
  skip: process.env.OPUS_PHASE_TEST !== '1' && 'Set OPUS_PHASE_TEST=1 to run GCC (WSL on Windows) against the independent reference.',
  timeout: 300000,
}, async () => {
  assert.equal((await runPhaseRegressions()).passed, true);
});
