const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const f=require('../tools/esp8266_opus_asm/mdct_three_pair.cjs'),base=require('../tools/esp8266_opus_asm/frozen_reloads.cjs'),{hash}=require('../tools/esp8266_opus_asm/export.cjs'),report=require('../tools/esp8266_opus_asm/report_mdct_three_pair.cjs');
const proof=f.read(path.join(f.art('candidate'),'preflight.json')),p=proof.patches[0],old=proof.functions[f.names[0]].disassembly,now=proof.actual_functions[f.names[0]].disassembly;
test('all450 table pairs preserve arbitrary32-bit PCM and separately rounded multiply terms',()=>{assert.deepEqual(f.prove(old,now,p,proof.tables),proof.symbolicProof);assert.equal(proof.symbolicProof.pairs,450);assert.deepEqual(proof.symbolicProof.table_loads_per_pair,{old:6,new:3});
 for(const [a,b]of [['srai\ta11, a11, 15','srai\ta11, a11, 14'],['srai\ta10, a14, 16','srai\ta10, a15, 16'],['sub\ta4, a4, a8','add\ta4, a4, a8'],['l32i.n\ta9, a1, 12','l32i.n\ta9, a1, 8']]){const bad=now.replace(a,b);assert.notEqual(bad,now);assert.throws(()=>f.prove(old,bad,p,proof.tables));}});
test('parity, pointer advance, loop targets and boundary ABI mutations fail',()=>{for(const [a,b]of [['bbsi\ta12, 1,','bbsi\ta12, 2,'],['addi.n\ta12, a12, 2','addi.n\ta12, a12, 4'],['mov.n\ta15, a9','mov.n\ta15, a0'],['addi\ta1, a1, -96','addi\ta1, a1, -112']]){const bad=now.replace(a,b);assert.notEqual(bad,now);assert.throws(()=>f.prove(old,bad,p,proof.tables));}});
test('all four linked trig/bitrev ranges share parity, are immutable and bounded',()=>{const elf=zlib.gunzipSync(fs.readFileSync(path.join(f.art('candidate'),'parent.elf.gz')));report.tableWords(elf,proof.tables);
 for(const mutate of [t=>t.supported_standard_transforms[0].t0+=2,t=>t.supported_standard_transforms[1].t1+=4,t=>t.supported_standard_transforms[3].n=59,t=>t.trig+=4]){const t=structuredClone(proof.tables);mutate(t);assert.throws(()=>report.tableWords(elf,t));}});
test('numeric full transforms agree for PCM32 edge cases, random data, strides and aliasing',()=>{const elf=zlib.gunzipSync(fs.readFileSync(path.join(f.art('candidate'),'parent.elf.gz'))),{wordOffset}=require('../tools/esp8266_opus_asm/frozen_div.cjs');let seed=7349,cases=0;const random=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return seed>>>0;};const edges=[0,1,0xffffffff,0x7fffffff,0x80000000,32767,32768,65535,0xffff0000,0x40000001];
 const select=s=>base.rows(s).filter(r=>r.address>=p.address&&r.address<p.address+p.bytes);
 for(const t of proof.tables.supported_standard_transforms)for(const stride of [1,2])for(const alias of [false,true]){const sp=0x3ffe0000,xp1=0x3ffe1000,xp2=0x3ffe1000+(t.n*2-1)*4*stride,yp=alias?xp1:0x3fff0000,regs=Object.fromEntries(Array.from({length:16},(_,i)=>['a'+i,random()]));Object.assign(regs,{a1:sp,a3:xp1,a12:t.address,a13:t.t1});
  const mem=new Map([[sp+32,(-2*t.n)>>>0],[sp+4,xp2],[sp+12,yp],[sp+24,(-8*stride)>>>0],[sp+8,8*stride],[sp+28,t.address+t.n*2]]);
  for(let i=0;i<t.n;i++){mem.set(xp1+i*8*stride,i<edges.length?edges[i]:random());mem.set(xp2-i*8*stride,i<edges.length?edges.at(-i-1):random());}
  for(const start of [t.address,t.t0,t.t1])for(let i=0;i<t.n*2;i+=4)mem.set(start+i,elf.readUInt32LE(wordOffset(elf,start+i)));
  const a=f.interpret(select(old),p,regs,mem,t.n),b=f.interpret(select(now),p,regs,mem,t.n);assert.deepEqual(b.writes,a.writes);for(const r of ['a1','a3','a9','a12','a13'])assert.equal(b.state[r],a.state[r]);cases++;}
 assert.equal(cases,16);});
test('one193-byte range changes; RAM, frame, rest of ELF/app and settings stay fixed',()=>{const {manifests}=report.verifyPair();const a=zlib.gunzipSync(fs.readFileSync(path.join(f.art('candidate'),'parent.elf.gz'))),b=base.patchElf(a,[p]);assert.equal(hash(b),proof.candidate_elf_sha256);assert.equal(p.bytes,193);assert.equal(proof.static_ram_delta,0);assert.equal(proof.stack_delta,0);assert.equal(proof.symbolicProof.frame_bytes,96);
 for(const mutate of [m=>m.cpu_mhz=80,m=>m.flash='QIO80',m=>m.opus_benchmark_output=true,m=>m.opus_function_profile=true,m=>m.opus_profile_stage=1]){const b=structuredClone(manifests.candidate);mutate(b);assert.throws(()=>f.manifestPair(manifests.control,b));}});
