const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const f=require('../tools/esp8266_opus_asm/mdct_mul16.cjs'),base=require('../tools/esp8266_opus_asm/frozen_reloads.cjs'),report=require('../tools/esp8266_opus_asm/report_mdct_mul16.cjs'),{hash}=require('../tools/esp8266_opus_asm/export.cjs');
const proof=f.read(path.join(f.art('candidate'),'preflight.json')),old=proof.functions[f.names[0]].disassembly,now=proof.actual_functions[f.names[0]].disassembly;
test('fixed-point signed-width proof selects exactly16 safe products, never unsigned low16',()=>{const p=f.findPatches(proof.functions[f.names[0]]);assert.deepEqual(p.analysis,proof.analysis);assert.equal(p.patches.length,16);assert.ok(p.analysis.products.filter(x=>x.eligible).every(x=>x.widths.every(w=>w<=16)));assert.ok(p.analysis.products.some(x=>x.widths.includes(17)&&!x.eligible));
 const bad=old.replace('srai\ta8, a2, 16','srai\ta8, a2, 15');assert.notEqual(bad,old);assert.throws(()=>f.findPatches({...proof.functions[f.names[0]],disassembly:bad}));});
test('all branch paths and loop backedges join widths; calls and unknown instructions fail safely',()=>{
 const join='1000: 000000 srai a2, a2, 16\n1003: 000000 beq a4, a5, 100c <join>\n1006: 000000 l32i a2, a1, 0\n1009: 000000 j 100c <join>\n100c: 000000 srai a3, a3, 16\n100f: 000000 mull a2, a2, a3\n1012: f00d ret.n';
 assert.deepEqual(f.widths(join).products[0].widths,[32,16]);assert.equal(f.widths(join).products[0].eligible,false);
 const loop='1000: 000000 srai a2, a2, 16\n1003: 000000 srai a3, a3, 16\n1006: 000000 mull a6, a2, a3\n1009: 000000 l32i a2, a1, 0\n100c: 000000 beq a4, a5, 1003 <loop>\n100f: f00d ret.n';assert.deepEqual(f.widths(loop).products[0].widths,[32,16]);
 const call='1000: 000000 srai a2, a2, 16\n1003: 000000 srai a3, a3, 16\n1006: 000000 call0 2000 <opus_fft_impl>\n1009: 000000 mull a6, a2, a3\n100c: f00d ret.n';assert.deepEqual(f.widths(call).products[0].widths,[32,32]);
 assert.throws(()=>f.widths(call.replace('<opus_fft_impl>','<unknown>')));assert.throws(()=>f.widths(join.replace('l32i a2','unknown a2')),/Unproved/);assert.throws(()=>f.widths(join.replace('100c <join>','9000 <bad>')),/CFG/);});
test('589824 integer edge products match exact BigInt, with full-domain algebraic bound',()=>{assert.deepEqual(f.numericProof(),proof.numeric);assert.equal(proof.numeric.cases,589824);assert.notEqual(Math.imul(65535,12345),Math.imul(-1,12345),'Unsigned low16 must not be narrowed');});
test('actual opcodes change only MULL into same-width MUL16S, preserving CFG and ABI',()=>{assert.deepEqual(f.validateActual(old,now,proof.patches),proof.actualAnalysis);
 for(const [a,b]of [['mul16s\ta7, a10, a8','mul16s\ta7, a10, a2'],['addi\ta1, a1, -96','addi\ta1, a1, -112'],['mull\ta11, a10, a2','mul16s\ta11, a10, a2']]){const bad=now.replace(a,b);assert.notEqual(now,bad);assert.throws(()=>f.validateActual(old,bad,proof.patches));}});
test('sixteen3-byte patches preserve other ELF/app bytes, RAM, stack and benchmark settings',()=>{const {manifests}=report.verifyPair(),a=zlib.gunzipSync(fs.readFileSync(path.join(f.art('candidate'),'parent.elf.gz'))),b=base.patchElf(a,proof.patches);assert.equal(hash(b),proof.candidate_elf_sha256);assert.equal(proof.static_ram_delta,0);assert.equal(proof.stack_delta,0);assert.ok(proof.patches.every(p=>p.bytes===3));
 for(const mutate of [m=>m.cpu_mhz=80,m=>m.flash='QIO80',m=>m.opus_benchmark_output=true,m=>m.opus_function_profile=true,m=>m.opus_profile_stage=1,m=>m.post_link_three_pair_variant='control']){const b=structuredClone(manifests.candidate);mutate(b);assert.throws(()=>f.manifestPair(manifests.control,b));}});
