# After project(): replace one SDK translation unit, never mutate the SDK.
if(NOT YORADIO_OPUS_FUNCTION_PROFILE)
  return()
endif()
get_filename_component(opus_profile_sdk "$ENV{IDF_PATH}" REALPATH)
set(opus_profile_tasks "${opus_profile_sdk}/components/freertos/freertos/tasks.c")
idf_component_get_property(opus_profile_target freertos COMPONENT_LIB)
get_target_property(opus_profile_sources ${opus_profile_target} SOURCES)
set(opus_profile_new_sources "")
set(opus_profile_matches 0)
foreach(src IN LISTS opus_profile_sources)
  if(src STREQUAL opus_profile_tasks)
    math(EXPR opus_profile_matches "${opus_profile_matches}+1")
    list(APPEND opus_profile_new_sources "${CMAKE_BINARY_DIR}/opus-function-sdk/tasks.c")
  else()
    list(APPEND opus_profile_new_sources "${src}")
  endif()
endforeach()
if(NOT opus_profile_matches EQUAL 1)
  message(FATAL_ERROR "Expected exactly one SDK tasks.c for function-profile adapter")
endif()
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/opus-function-sdk")
# Keep the original archive member basename: SDK linker.lf selects tasks BSS.
configure_file("${CMAKE_CURRENT_LIST_DIR}/opus_task_clock.c.in" "${CMAKE_BINARY_DIR}/opus-function-sdk/tasks.c" @ONLY)
set_property(TARGET ${opus_profile_target} PROPERTY SOURCES "${opus_profile_new_sources}")
set_source_files_properties("${CMAKE_BINARY_DIR}/opus-function-sdk/tasks.c" PROPERTIES COMPILE_DEFINITIONS _ESP_FREERTOS_INTERNAL)
