# Included after project(): component targets and their absolute SOURCES exist.
if(NOT YORADIO_ESP8266_SDK_RX_DIAG)
  return()
endif()
if(NOT YORADIO_ESP8266_DIAGNOSTIC)
  message(FATAL_ERROR "SDK RX diagnostics require YORADIO_ESP8266_DIAGNOSTIC=ON")
endif()
get_filename_component(rx_diag_project "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(rx_diag_sdk "$ENV{IDF_PATH}" REALPATH)
set(rx_diag_generator "${rx_diag_project}/../../tools/esp8266_audio_profile/build_sdk_rx_diag.cjs")
set(rx_diag_output "${CMAKE_BINARY_DIR}/sdk-rxdiag")
find_program(YORADIO_RX_DIAG_NODE NAMES node node.exe)
if(NOT YORADIO_RX_DIAG_NODE)
  message(FATAL_ERROR "SDK RX diagnostic overlay generation requires Node.js")
endif()

# Validate exact target membership BEFORE generation. No full lwIP fork, global
# SDK mutation, or extra copy of an original object may slip into the build.
set(rx_diag_sources
  "components/tcpip_adapter/tcpip_adapter_lwip.c"
  "components/lwip/lwip/src/api/tcpip.c"
  "components/lwip/port/esp8266/netif/wlanif.c")
set(rx_diag_components tcpip_adapter lwip lwip)
foreach(rx_diag_index RANGE 0 2)
  list(GET rx_diag_sources ${rx_diag_index} rx_diag_relative)
  list(GET rx_diag_components ${rx_diag_index} rx_diag_component)
  idf_component_get_property(rx_diag_target ${rx_diag_component} COMPONENT_LIB)
  get_target_property(rx_diag_originals ${rx_diag_target} SOURCES)
  set(rx_diag_matches 0)
  foreach(rx_diag_source IN LISTS rx_diag_originals)
    if(rx_diag_source STREQUAL "${rx_diag_sdk}/${rx_diag_relative}")
      math(EXPR rx_diag_matches "${rx_diag_matches} + 1")
    endif()
  endforeach()
  if(NOT rx_diag_matches EQUAL 1)
    message(FATAL_ERROR "SDK RX overlay expected exactly one ${rx_diag_relative} in ${rx_diag_target}, got ${rx_diag_matches}")
  endif()
endforeach()

execute_process(COMMAND "${YORADIO_RX_DIAG_NODE}" "${rx_diag_generator}"
  --sdk "${rx_diag_sdk}" --out "${rx_diag_output}"
  RESULT_VARIABLE rx_diag_result OUTPUT_VARIABLE rx_diag_stdout ERROR_VARIABLE rx_diag_stderr)
if(NOT rx_diag_result EQUAL 0)
  message(FATAL_ERROR "SDK RX diagnostic overlay refused: ${rx_diag_stderr}")
endif()
message(STATUS "${rx_diag_stdout}")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${rx_diag_generator}")
foreach(rx_diag_index RANGE 0 2)
  list(GET rx_diag_sources ${rx_diag_index} rx_diag_relative)
  list(GET rx_diag_components ${rx_diag_index} rx_diag_component)
  idf_component_get_property(rx_diag_target ${rx_diag_component} COMPONENT_LIB)
  get_target_property(rx_diag_originals ${rx_diag_target} SOURCES)
  get_filename_component(rx_diag_basename "${rx_diag_relative}" NAME)
  set(rx_diag_replaced "")
  foreach(rx_diag_source IN LISTS rx_diag_originals)
    if(rx_diag_source STREQUAL "${rx_diag_sdk}/${rx_diag_relative}")
      list(APPEND rx_diag_replaced "${rx_diag_output}/${rx_diag_basename}")
    else()
      list(APPEND rx_diag_replaced "${rx_diag_source}")
    endif()
  endforeach()
  set_property(TARGET ${rx_diag_target} PROPERTY SOURCES "${rx_diag_replaced}")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${rx_diag_sdk}/${rx_diag_relative}")
endforeach()
foreach(rx_diag_component tcpip_adapter lwip)
  idf_component_get_property(rx_diag_target ${rx_diag_component} COMPONENT_LIB)
  target_include_directories(${rx_diag_target} PRIVATE "${rx_diag_project}/main")
  target_compile_definitions(${rx_diag_target} PRIVATE YORADIO_ESP8266_SDK_RX_DIAG=1)
endforeach()
