set(YORADIO_ESP8266_WEB_AUDIO_PAUSE "off" CACHE STRING
    "HTTP audio policy: off, short (priority), long (release and reconnect)")
set_property(CACHE YORADIO_ESP8266_WEB_AUDIO_PAUSE PROPERTY STRINGS off short long)
if(YORADIO_ESP8266_WEB_AUDIO_PAUSE STREQUAL "off")
  set(WEB_AUDIO_PAUSE_MODE 0)
elseif(YORADIO_ESP8266_WEB_AUDIO_PAUSE STREQUAL "short")
  set(WEB_AUDIO_PAUSE_MODE 1)
elseif(YORADIO_ESP8266_WEB_AUDIO_PAUSE STREQUAL "long")
  set(WEB_AUDIO_PAUSE_MODE 2)
  if(YORADIO_ESP8266_KARADIO_PIPELINE)
    message(FATAL_ERROR "Long WebUI pause requires the native single-owner audio pipeline")
  endif()
else()
  message(FATAL_ERROR "YORADIO_ESP8266_WEB_AUDIO_PAUSE must be off, short or long")
endif()
