// Frozen-layout ec_dec_bits low-bit extraction ASM; original C and saved GCC snapshot unchanged.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),zlib=require('node:zlib');
const {root,component,hash,sourceHash,run}=require('./export.cjs'),base=require('./frozen_reloads.cjs'),post=require('./pvq_row_loop.cjs'),sem=require('./ec_bits_proof.cjs');
const {sections,inspectImage}=require('./frozen_div.cjs'),{inspect}=require('./report_layout.cjs');
const parent=post.variant('candidate'),variant=t=>'esp8266-opus-ec-bits-'+t+'-v1';
const art=t=>path.join(root,'firmware/development',variant(t)),build=t=>path.join(root,'.build',variant(t)),names=[...new Set(['ec_dec_bits',...post.names])],read=post.read;
const sourceFile=path.join(__dirname,'ec_bits.s'),proofFile=path.join(__dirname,'ec_bits_proof.cjs');
const bin='C:/Work/yoRadio/.build/esp8266-tools/tools/xtensa-lx106-elf/esp-2020r3-49-gd5524c1-8.4.0/xtensa-lx106-elf/bin',python='C:/Work/yoRadio/.build/esp8266-python/Scripts/python.exe',esptool='C:/Work/yoRadio/.worktree/esp8266-native-port/.build/esp8266-rtos-sdk/components/esptool_py/esptool/esptool.py';
function save(p,b){if(typeof b==='string')b=Buffer.from(b);fs.mkdirSync(path.dirname(p),{recursive:true});if(fs.existsSync(p))assert.deepEqual(fs.readFileSync(p),b,'Existing evidence differs: '+p);else fs.writeFileSync(p,b);}
function findPatch(fn){sem.audit(fn,sem.oldOps);return{address:sem.address,bytes:sem.bytes};}
function manifestPair(a,b){assert.equal(a.post_link_ec_bits_variant,'control');assert.equal(b.post_link_ec_bits_variant,'candidate');for(const k of new Set([...Object.keys(a),...Object.keys(b)]))if(!['purpose','app_sha256','post_link_ec_bits_variant'].includes(k))assert.deepEqual(a[k],b[k],k);
 for(const m of[a,b]){assert.equal(m.post_link_pvq_row_loop_variant,'candidate');assert.equal(m.post_link_post_pair_variant,'candidate');assert.equal(m.post_link_mdct_variant,'candidate');assert.equal(m.opus_backend,'bands-tell-inline-asm');assert.equal(m.diagnostic,true);assert.equal(m.cpu_mhz,160);assert.equal(m.flash,'QIO40');assert.equal(m.opus_benchmark,true);assert.equal(m.opus_benchmark_output,false);assert.equal(m.opus_function_profile,false);assert.equal(m.opus_profile_stage,0);assert.equal(m.opus_division_benchmark,false);}}
function generate(){const prior=require('./report_pvq_row_loop.cjs').verifyPair(),dir=path.join(root,'firmware/development',parent),m=read(path.join(dir,'manifest.json')),file=path.join(root,'.build',parent,base.elfName),a=fs.readFileSync(file),app=fs.readFileSync(path.join(dir,'app.bin'));assert.equal(hash(a),prior.proof.candidate_elf_sha256);assert.equal(hash(app),m.app_sha256);
 const info=inspect(parent,names),fn=info.functions[names[0]],p=findPatch(fn),source=fs.readFileSync(sourceFile,'utf8').replace(/\r\n/g,'\n');
 fs.mkdirSync(build('candidate'),{recursive:true});const asm=path.join(build('candidate'),'patches.s'),obj=path.join(build('candidate'),'patches.o'),linked=path.join(build('candidate'),'patches.elf'),script=path.join(build('candidate'),'patches.ld');save(asm,source);save(script,`SECTIONS { .text.patch0 0x${p.address.toString(16)} : { *(.text.patch0) } }\n`);run(path.join(bin,'xtensa-lx106-elf-as.exe'),[asm,'-o',obj]);run(path.join(bin,'xtensa-lx106-elf-ld.exe'),['-e','0','-T',script,'-o',linked,obj]);const object=fs.readFileSync(linked),s=sections(object).find(s=>s.name==='.text.patch0');assert.equal(s.address,p.address);assert.equal(s.bytes,p.bytes);p.after_hex=object.subarray(s.offset,s.offset+s.bytes).toString('hex');const off=base.offsetAt(a,p.address,p.bytes);p.before_hex=a.subarray(off,off+p.bytes).toString('hex');
 const b=base.patchElf(a,[p]),images={},manifests={},logs={};for(const[t,bytes]of[['control',a],['candidate',b]]){const to=path.join(build(t),base.elfName);save(to,bytes);logs[t]=run(python,[esptool,'--chip','esp8266','elf2image','--flash_mode','dio','--flash_freq','40m','--flash_size','4MB','--version=3','-o',path.join(build(t),'app.bin'),to]);images[t]=fs.readFileSync(path.join(build(t),'app.bin'));inspectImage(images[t]);assert.ok(images[t].length<=0xf0000);
  manifests[t]={...m,purpose:'Frozen-layout '+t+' ec_dec_bits low-bit extraction ASM benchmark; not production',app_sha256:hash(images[t]),post_link_ec_bits_variant:t,post_link_recipe_sha256_lf:sourceHash(__filename),post_link_asm_sha256_lf:sourceHash(sourceFile),post_link_proof_sha256_lf:sourceHash(proofFile),post_link_parent_app_sha256:hash(app),post_link_parent_elf_sha256:hash(a)};}
 assert.deepEqual(images.control,app);manifestPair(manifests.control,manifests.candidate);const actual=inspect(variant('candidate'),names);assert.deepEqual(actual.sections,info.sections);assert.deepEqual(actual.function_sizes,info.function_sizes);const symbolic=sem.prove(fn,actual.functions[names[0]]);for(const n of names.slice(1))assert.deepEqual(actual.functions[n],info.functions[n]);
 const proof={schema:1,parent,recipe_sha256_lf:sourceHash(__filename),asm_sha256_lf:sourceHash(sourceFile),proof_sha256_lf:sourceHash(proofFile),parent_elf_sha256:hash(a),candidate_elf_sha256:hash(b),patches:[p],symbolic,static_ram_delta:0,stack_delta:0,app_bytes:app.length,sections:actual.sections,functions:info.functions,actual_functions:actual.functions,imageProof:base.compareApps(images.control,images.candidate,[p]),packaging:{esptool_sha256:hash(fs.readFileSync(esptool)),logs}};
 for(const t of['control','candidate']){save(path.join(art(t),'app.bin'),images[t]);save(path.join(art(t),'manifest.json'),JSON.stringify(manifests[t],null,2)+'\n');save(path.join(art(t),'sdkconfig'),fs.readFileSync(path.join(dir,'sdkconfig')));}save(path.join(art('candidate'),'parent.elf.gz'),zlib.gzipSync(a,{level:9}));save(path.join(art('candidate'),'patches.s'),source);save(path.join(art('candidate'),'patches.elf'),object);save(path.join(art('candidate'),'preflight.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({passed:true,sha256:manifests.candidate.app_sha256,app_bytes:app.length,ram_delta:0,symbolic}));return proof;}
function cModels(){const source='upstream/celt/entdec.c',file=path.join(root,'.build/opus-bands-ec-bits/entdec.c'),original=fs.readFileSync(path.join(component,source),'utf8'),needle='ret=(opus_uint32)window&(((opus_uint32)1<<_bits)-1U);';
 assert.equal(original.split(needle).length,2);const text=original.replace(needle,'/* Host semantic mirror of ec_bits.s, not the target implementation. */\n  ret=(opus_uint32)window ^ (((opus_uint32)window >> _bits) << _bits);');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text);return[{source,file}];}
module.exports={cModels,parent,variant,art,build,names,read,sourceFile,proofFile,findPatch,manifestPair,generate};if(require.main===module)generate();
