// Decoder-only specialization of actual saved-GCC linked instructions.
// Freeze every byte outside quant_partition; preserve ROM callx and literals.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {root,component,sourceHash}=require('./export.cjs'),base=require('./frozen_reloads.cjs');
const {analyze}=require('./partition_decode.cjs'),{project}=require('./audit_partition_decode.cjs'),{normal}=require('./report_small_div_inline.cjs');
const target=r=>{const m=r.args.match(/(?:^|,\s*)([0-9a-f]+)\s+<[^>]*>$/);assert.ok(m,r.text);return parseInt(m[1],16);};
function program(fn){const rows=base.rows(fn.disassembly),labels=Object.fromEntries(rows.map((r,i)=>['pc'+r.address.toString(16),i]));
 const ops=rows.map((r,i)=>{let op=r.op.replace(/\.n$/,''),args=r.args.replace(/\s+<[^>]*>$/,'').split(/,\s*/);
  if(/^b|^j$/.test(op)){args[args.length-1]='pc'+target(r).toString(16);assert.ok(Object.hasOwn(labels,args.at(-1)));}
  if(op==='callx0'){assert.equal(r.args,'a0');const prior=rows[i-1];assert.equal(prior.op,'l32r');assert.match(prior.args,/^a0,/);assert.equal(prior.address+prior.bytes,r.address);
   for(const branch of rows.filter(q=>/^b|^j$/.test(q.op)))assert.notEqual(target(branch),r.address,'Bypassed indirect-call literal');op='call0';args=['indirect-via-pinned-literal'];}
  return{op,args,row:i,text:r.text};});return{rows,labels,ops};}
function compile(fn){assert.equal(fn.address,0x4024dafc);assert.equal(fn.bytes,2382);const p=program(fn),analysis=analyze(p);assert.equal(analysis.branches.length,3);
 const unknown=analyze(p,{encodeZero:false});assert.equal(unknown.branches.length,0);assert.equal(unknown.dead.length,0);
 const dead=new Set(analysis.dead.map(d=>d.index)),branches=new Map(analysis.branches.map(b=>[b.index,b]));const next=i=>{while(dead.has(i))i++;assert.ok(i<p.rows.length);return i;};
 const definitions=new Map(),records=[];let text='# Frozen-layout quant_partition, saved GCC ASM; decoder-only ctx.encode=0.\n# LX106 call0 ABI, original112-byte stack/callee saves and arithmetic.\n# ROM L32R/CALLX0 pairs retained; no added RAM, no bitrate/mode limit.\n# Only proven encoder branches/dead code removed; all audio branches kept.\n# Generated by partition_frozen_proof.cjs; original C/GCC sources unchanged.\n.section .text.patch0,"ax",@progbits\n.begin no-transform\n';
 for(const[rindex,r]of p.rows.entries()){
  text+='pc'+r.address.toString(16)+':\n';if(dead.has(rindex)){text+='# unreachable encoder instruction: '+r.text+'\n';continue;}
  const b=branches.get(rindex);if(b&&(!b.taken||b.target===next(rindex+1))){text+='# proven encode=0 check removed: '+r.text+'\n';continue;}
  let op=b?'j':r.op,args=b?p.ops[b.target]&&'pc'+p.rows[b.target].address.toString(16):r.args.replace(/\s+<[^>]*>$/,'');
  if(!b&&(/^b|^j$/.test(op)))args=args.replace(/[0-9a-f]+$/,'pc'+target(r).toString(16));
  else if(!b&&(op==='l32r'||op==='call0')){const t=target(r),symbol='fixed_'+t.toString(16);
   if(op==='l32r'){assert.equal(t%4,0);assert.ok(t<fn.address||t>=fn.address+fn.bytes,'Literal inside replaced code');}
   else assert.ok(t===fn.address||t<fn.address||t>=fn.address+fn.bytes,'Call to internal instruction');
   definitions.set(symbol,t);args=args.replace(/[0-9a-f]+$/,symbol);}
  text+=op+' '+args+' # original0x'+r.address.toString(16)+'\n';records.push({source_address:r.address,op,args});
 }
 assert.equal(records.at(-1).op,'ret.n');text+='frozen_live_end:\n.space '+fn.bytes+' - (. - pc'+fn.address.toString(16)+'), 0\n.end no-transform\n';
 const script=[...definitions].map(([s,a])=>s+' = 0x'+a.toString(16)+';').join('\n')+'\nSECTIONS { .text.patch0 0x'+fn.address.toString(16)+' : { *(.text.patch0) } }\n';
 return{text,script,records,analysis:{branches:analysis.branches,removed_raw_instructions:analysis.dead.length},references:[...definitions].map(([symbol,address])=>({symbol,address}))};}
function contract(info){const old=JSON.parse(fs.readFileSync(path.join(root,'firmware/development/esp8266-opus-partition-decode-v1/preflight.json')));
 for(const name of['quant_partition','quant_band','quant_all_bands','celt_decode_with_ec_dred'])assert.deepEqual(normal(info.functions[name].graph),normal(old.reference.functions[name].graph),'Unchanged decoded caller contract '+name);
 require('./verify.cjs').verify('bands-partition-decode-asm');
 const bandsFile=path.join(component,'upstream/celt/bands.c'),bands=fs.readFileSync(bandsFile,'utf8');
 assert.deepEqual([...bands.matchAll(/ctx(?:\.|->)encode\s*=(?!=)[^;]*;/g)].map(m=>m[0]),['ctx.encode = encode;']);
 assert.deepEqual([...bands.matchAll(/ctx\s*=\s*ctx_save\d*;/g)].map(m=>m[0]),['ctx = ctx_save;','ctx = ctx_save2;']);
 const g=normal(info.functions.celt_decode_with_ec_dred.graph),calls=g.flatMap((s,i)=>s==='call0 quant_all_bands'?[i]:[]);assert.equal(calls.length,1);const index=calls[0];let previous=index-1,needed='a2';
 for(;previous>=0;previous--){const s=g[previous];assert.doesNotMatch(s,/^(?:b|j |ret |call0 )/);if(new RegExp('^mov '+needed+', a[0-9]+$').test(s)){needed=s.split(', ')[1];continue;}if(new RegExp('^(?!s(?:8|16|32)i )\\S+ '+needed+',').test(s)){assert.equal(s,'movi '+needed+', 0');break;}}
 assert.ok(previous>=0);for(const s of g)for(const m of s.matchAll(/instruction:(\d+)/g))assert.ok(+m[1]<=previous||+m[1]>index,'Bypassed encode=0');
 return{scope:'Same pinned decoder call chain/private ctx contract as prior independently audited specialization; no encoder API.',bands_source_sha256_lf:sourceHash(bandsFile),argument:g.slice(previous,index+1),previous_cross_reference:old.call_chain.cross_reference};}
function prove(before,after){const a=project(normal(before.graph)),b=project(normal(after.graph));assert.equal(a.branches.length,3);assert.equal(b.branches.length,0);assert.deepEqual(a.graph,b.graph,'Decoder instructions, CFG, constants, widths and calls');
 assert.equal(before.address,after.address);assert.equal(before.bytes,after.bytes);const old=program(before),now=program(after);assert.equal(now.rows.at(-1).op,'ret.n');
 const retained=compile(before),liveEnd=now.rows.at(-1).address+now.rows.at(-1).bytes;assert.ok(liveEnd<=before.address+before.bytes);
 const external=rows=>rows.filter(r=>r.op==='l32r'||r.op==='call0').map(r=>({op:r.op,target:target(r)}));
 const kept=new Set(retained.records.map(r=>r.source_address));assert.deepEqual(external(now.rows),external(old.rows.filter(r=>kept.has(r.address))),'Exact retained literal/call addresses and order');
 assert.equal(now.rows.filter(r=>r.op==='callx0').length,old.rows.filter(r=>r.op==='callx0'&&kept.has(r.address)).length);
 return{removed_linked_instructions:a.dead,projected:a.graph,constant_branches:a.branches,live_bytes:liveEnd-before.address,padding_bytes:before.address+before.bytes-liveEnd,callx_pairs_before:old.rows.filter(r=>r.op==='callx0').length,callx_pairs_after:now.rows.filter(r=>r.op==='callx0').length,references:retained.references};}
module.exports={target,program,compile,contract,prove};
