const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),assert=require('node:assert/strict');
const {root,hash,sourceHash}=require('./export.cjs'),f=require('./mdct_bitrev_pair.cjs'),base=require('./frozen_reloads.cjs');
const {sections,wordOffset}=require('./frozen_div.cjs'),{archive}=require('./report_bands.cjs'),{validateRun}=require('./report_small_div_tail.cjs');
const {compare}=require('../esp8266_opus_profile/compare_raw.cjs'),{selectHighBitrate}=require('./selection.cjs');
const dest=f.art('candidate'),experiment=path.join(root,'.build/opus-mdct-bitrev-pair-board');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
function tableWords(elf,t){const word=a=>elf.readUInt32LE(wordOffset(elf,a)),m=t.mode.address;assert.equal(word(m),48000);assert.equal(word(m+56),1920);assert.equal(word(m+60),3);
 assert.deepEqual(t.supported_standard_transforms.map(x=>x.n),[480,240,120,60]);for(const x of t.supported_standard_transforms){assert.equal(x.address%4,0);assert.equal(x.bytes,x.n*2);const state=word(m+64+x.shift*4);assert.equal(word(state),x.n);assert.equal(word(state+48),x.address);const off=wordOffset(elf,x.address),bytes=elf.subarray(off,off+x.bytes);assert.equal(hash(bytes),x.sha256);assert.deepEqual(Array.from({length:x.n},(_,i)=>bytes.readInt16LE(i*2)),x.values);assert.equal(x.old_loads,x.n);assert.equal(x.new_loads,x.n/2);}
}
function verifyPair(){const proof=read(path.join(dest,'preflight.json'));assert.equal(proof.recipe_sha256_lf,sourceHash(path.join(__dirname,'mdct_bitrev_pair.cjs')));const a=zlib.gunzipSync(fs.readFileSync(path.join(dest,'parent.elf.gz')));assert.equal(hash(a),proof.parent_elf_sha256);assert.equal(proof.patches.length,1);
 const fn=f.names[0],p=f.findPatch(proof.functions[fn]),{before_hex,after_hex,...saved}=proof.patches[0];assert.deepEqual(p,saved);const b=base.patchElf(a,proof.patches);assert.equal(hash(b),proof.candidate_elf_sha256);
 const object=fs.readFileSync(path.join(dest,'patches.elf')),sec=sections(object).find(s=>s.name==='.text.patch0');assert.equal(sec.address,p.address);assert.equal(sec.bytes,p.bytes);assert.equal(object.subarray(sec.offset,sec.offset+sec.bytes).toString('hex'),after_hex);assert.equal(after_hex.slice(-8),'00000000');
 const old=proof.functions[fn].disassembly,now=proof.actual_functions[fn].disassembly;f.validateActual(old,now,p);assert.deepEqual(f.prove(old,now,p),proof.symbolicProof);assert.deepEqual(f.liveness(proof.functions[fn],p),proof.liveness);tableWords(a,proof.tables);tableWords(b,proof.tables);
 for(const name of f.names.slice(1))assert.deepEqual(proof.actual_functions[name],proof.functions[name]);const manifests={},apps={};for(const t of ['control','candidate']){manifests[t]=read(path.join(f.art(t),'manifest.json'));apps[t]=fs.readFileSync(path.join(f.art(t),'app.bin'));assert.equal(hash(apps[t]),manifests[t].app_sha256);assert.equal(apps[t].length,manifests[t].bytes);assert.equal(manifests[t].post_link_recipe_sha256_lf,proof.recipe_sha256_lf);}
 f.manifestPair(manifests.control,manifests.candidate);assert.deepEqual(base.compareApps(apps.control,apps.candidate,proof.patches),proof.imageProof);assert.equal(hash(apps.control),require('./report_mdct_half.cjs').verifyPair().manifests.candidate.app_sha256);return {proof,manifests};}
function report(){const pair=verifyPair(),groups={},fixtures=read(path.join(root,'firmware/development/esp8266-opus-asm-library/fixtures/manifest.json'));
 for(const [name,dir]of [['before','controls/before'],['candidate','runs'],['after','controls/after']]){const ota=read(path.join(experiment,'ota-'+name+'.json'));assert.equal(ota.pass,true);assert.equal(ota.sha256,pair.manifests[name==='candidate'?'candidate':'control'].app_sha256);const rows=archive(path.join(experiment,name),path.join(dest,dir));assert.equal(rows.length,10);for(const r of rows)validateRun(r.report,fixtures,ota.after.app_address);groups[name]=rows;fs.copyFileSync(path.join(experiment,'ota-'+name+'.json'),path.join(dest,'ota-'+name+'.json'));}
 const initial=compare(groups.before.map(r=>r.report),groups.candidate.map(r=>r.report)),repeated=compare(groups.after.map(r=>r.report),groups.candidate.map(r=>r.report));const result={pair,initial,repeated,selection:{initial:selectHighBitrate(initial.cases),repeated:selectHighBitrate(repeated.cases)},inputs:Object.fromEntries(Object.entries(groups).map(([k,rs])=>[k,rs.map(({report,...r})=>r)])),scope:'All30 frozen-layout bitrev A/B/A raw attempts retained; no network input, stage/function profiling or output; not live qualification.'};
 fs.writeFileSync(path.join(dest,'comparison.json'),JSON.stringify(result,null,2)+'\n');console.table(initial.cases.map((c,i)=>({name:c.name,A:c.reference.task_budget_percent.median,B:c.candidate.task_budget_percent.median,A2:repeated.cases[i].reference.task_budget_percent.median,reduction:c.median_task_reduction_percent})));console.log(JSON.stringify(result.selection));return result;}
module.exports={tableWords,verifyPair,report,experiment};if(require.main===module)report();
