const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { cases, fixtureDirectory, inspectPackets, sha256 } = require('./fixtures.cjs');
const { root, execute, hostPath } = require('./build_host.cjs');

const PACKETS_PER_FIXTURE = 12;
const MAX_PACKET_BYTES = 1536;
const defaultOutput = path.join(root, '.build/esp8266-opus-board-fixtures');
const defaultProbe = path.join(root, '.build/esp8266-opus-host-pristine/probe');

// Hash bytes, not signed samples or host-endian words. This matches a target
// loop that hashes (uint16_t)sample & 255, then (uint16_t)sample >> 8.
function fnv1a32(bytes) {
  let hash = 2166136261;
  for (const byte of bytes) hash = Math.imul(hash ^ byte, 16777619) >>> 0;
  return hash;
}

function selectPackets(data, count = PACKETS_PER_FIXTURE) {
  assert.ok(Number.isSafeInteger(count) && count > 0, 'Packet count must be positive');
  const packets = [];
  let offset = 0;
  while (packets.length < count) {
    assert.ok(offset + 2 <= data.length, 'Truncated packet length / insufficient packets');
    const length = data.readUInt16LE(offset);
    offset += 2;
    assert.ok(length > 0 && length <= MAX_PACKET_BYTES, 'Invalid or oversized packet');
    assert.ok(offset + length <= data.length, 'Truncated packet body');
    const packet = data.subarray(offset, offset + length);
    const framed = data.subarray(offset - 2, offset + length);
    const info = inspectPackets(framed);
    packets.push({ data: packet, samples: info.samples, duration_ms: info.samples / 48 });
    offset += length;
  }
  return { packets, framed: data.subarray(0, offset) };
}

function packPackets(packets) {
  const chunks = [], entries = [];
  let offset = 0;
  for (const packet of packets) {
    const data = packet.data || packet;
    const padded = Buffer.alloc((data.length + 3) & ~3);
    data.copy(padded);
    entries.push({ offset, length: data.length });
    chunks.push(padded);
    offset += padded.length;
  }
  return { payload: Buffer.concat(chunks), entries };
}

function renderHeader(payload, packets, fixtures) {
  assert.equal(payload.length % 4, 0);
  const words = [];
  for (let offset = 0; offset < payload.length; offset += 4)
    words.push('0x' + payload.readUInt32LE(offset).toString(16).padStart(8, '0') + 'U');
  const rows = [];
  for (let index = 0; index < words.length; index += 8)
    rows.push('    ' + words.slice(index, index + 8).join(', ') + ',');
  return `/* Generated by tools/esp8266_opus_profile/build_board_fixtures.cjs.
 * Raw Opus, fresh mono 48 kHz decoder per fixture, no Ogg pre-skip/EOS trim.
 * All tables are const uint32 fields: the ESP8266 linker keeps them in flash.
 * Copy with aligned word loads; do not use byte/halfword reads from flash.
 * Offsets are BYTES. Each packet is zero-padded to 4 bytes; length excludes it.
 * PCM hash: FNV-1a32 over signed 16-bit PCM's little-endian bytes.
 * Include this data header in only the benchmark implementation translation unit.
 */
#ifndef OPUS_BOARD_FIXTURES_H
#define OPUS_BOARD_FIXTURES_H
#include <stdint.h>

typedef struct { uint32_t offset, length; } opus_bench_packet_t;
typedef struct {
    uint32_t first_packet, packet_count, expected_hash, samples, bitrate_kbps;
} opus_bench_fixture_t;

#define OPUS_BENCH_FIXTURE_COUNT ${fixtures.length}U
#define OPUS_BENCH_PACKET_COUNT ${packets.length}U
#define OPUS_BENCH_PAYLOAD_BYTES ${payload.length}U

static const uint32_t opus_bench_payload[] __attribute__((aligned(4))) = {
${rows.join('\n')}
};
static const opus_bench_packet_t opus_bench_packets[] __attribute__((aligned(4))) = {
${packets.map(packet => `    { ${packet.offset}U, ${packet.length}U },`).join('\n')}
};
static const opus_bench_fixture_t opus_bench_fixtures[] __attribute__((aligned(4))) = {
${fixtures.map(fixture => `    { ${fixture.first_packet}U, ${fixture.packet_count}U, 0x${fixture.expected_hash.toString(16).padStart(8, '0')}U, ${fixture.samples}U, ${fixture.bitrate_kbps}U }, /* ${fixture.name} */`).join('\n')}
};
#endif
`;
}

function buildBoardFixtures({ output = defaultOutput, probe = defaultProbe } = {}) {
  const out = path.resolve(output), binary = path.resolve(probe);
  assert.ok(fs.existsSync(binary), 'Build the pristine host probe once before generating board fixtures');
  const buildFile = path.join(path.dirname(binary), 'build.json');
  assert.ok(fs.existsSync(buildFile), 'Pristine probe build.json is required for provenance');
  const build = JSON.parse(fs.readFileSync(buildFile, 'utf8'));
  assert.ok(!build.flags.some(flag => flag.includes('YORADIO_OPUS_BOUNDED')), 'Reference probe must be unbounded');
  const manifest = JSON.parse(fs.readFileSync(path.join(fixtureDirectory, 'manifest.json'), 'utf8'));
  const prepared = cases.map(([name, bitrate]) => {
    const data = fs.readFileSync(path.join(fixtureDirectory, name + '.opuspkt'));
    const expected = manifest.fixtures.find(fixture => fixture.name === name);
    assert.ok(expected, name + ' missing from corpus manifest');
    assert.equal(sha256(data), expected.opuspkt_sha256, name + ' source SHA-256 changed');
    return { name, bitrate, source: data, ...selectPackets(data) };
  });
  fs.mkdirSync(out, { recursive: true });
  const allPackets = prepared.flatMap(fixture => fixture.packets);
  const { payload, entries } = packPackets(allPackets);
  const fixtures = prepared.map((fixture, index) => {
    const input = path.join(out, fixture.name + '.opuspkt');
    const outputPcm = path.join(out, fixture.name + '.pcm');
    fs.writeFileSync(input, fixture.framed);
    // A separate probe process initializes a fresh decoder for every sequence.
    // Never invoke buildHost here or overwrite a shared probe's default output.
    const decoded = JSON.parse(execute(hostPath(binary), [hostPath(input), hostPath(outputPcm)]).trim());
    const pcm = fs.readFileSync(outputPcm);
    const samples = fixture.packets.reduce((total, packet) => total + packet.samples, 0);
    assert.equal(decoded.packets, PACKETS_PER_FIXTURE, fixture.name + ' decoded packet count');
    assert.equal(decoded.samples, samples, fixture.name + ' decoded sample count');
    assert.equal(decoded.output_channels, 1, 'Reference must decode mono');
    assert.equal(decoded.sample_rate, 48000, 'Reference must decode at 48 kHz');
    assert.equal(pcm.length, samples * 2, fixture.name + ' PCM byte count');
    return {
      name: fixture.name, bitrate_kbps: fixture.bitrate,
      first_packet: index * PACKETS_PER_FIXTURE, packet_count: PACKETS_PER_FIXTURE,
      expected_hash: fnv1a32(pcm), samples,
      source_opuspkt_sha256: sha256(fixture.source), source_bytes: fixture.source.length,
      selected_opuspkt_sha256: sha256(fixture.framed), selected_bytes: fixture.framed.length,
      pcm_sha256: sha256(pcm), pcm_bytes: pcm.length,
      packets: fixture.packets.map((packet, localIndex) => ({
        ...entries[index * PACKETS_PER_FIXTURE + localIndex],
        samples: packet.samples, duration_ms: packet.duration_ms, sha256: sha256(packet.data),
      })),
    };
  });
  const header = renderHeader(payload, entries, fixtures);
  const report = {
    schema_version: 1, packet_format: 'LP16LE input; header stores raw packets padded to 4 bytes',
    pcm_format: 'signed 16-bit little-endian mono, 48000 Hz; fresh decoder per fixture; no trim or PLC',
    hash_algorithm: 'FNV-1a32 over PCM bytes, offset basis 2166136261, prime 16777619',
    reference: { probe_sha256: sha256(fs.readFileSync(binary)), build_signature: build.signature, compiler: build.compiler },
    fixture_count: fixtures.length, packet_count: entries.length,
    payload_bytes: payload.length, table_bytes: entries.length * 8 + fixtures.length * 20,
    payload_sha256: sha256(payload), header_sha256: sha256(header), fixtures,
  };
  fs.writeFileSync(path.join(out, 'opus_board_fixtures.h'), header);
  fs.writeFileSync(path.join(out, 'manifest.json'), JSON.stringify(report, null, 2) + '\n');
  return report;
}

module.exports = { PACKETS_PER_FIXTURE, MAX_PACKET_BYTES, defaultOutput, defaultProbe,
  fnv1a32, selectPackets, packPackets, renderHeader, buildBoardFixtures };
if (require.main === module) {
  try {
    const value = key => { const index = process.argv.indexOf(key); return index < 0 ? undefined : process.argv[index + 1]; };
    const result = buildBoardFixtures({ output: value('--output-dir'), probe: value('--probe') });
    console.log(`Generated ${result.fixture_count} fixtures / ${result.packet_count} packets; ${result.payload_bytes + result.table_bytes} bytes flash data.`);
  } catch (error) { console.error(error.stack); process.exitCode = 1; }
}
