#pragma once

#include "driver/gpio.h"

// ESP32-C3 SuperMini OLED / 01Space-style 0.42-inch board.
#define BOARD_OLED_SDA GPIO_NUM_5
#define BOARD_OLED_SCL GPIO_NUM_6
#define BOARD_OLED_ADDRESS 0x3c
#define BOARD_OLED_CLOCK_HZ 400000
#define BOARD_OLED_CONTRAST 0x60

#define BOARD_AUDIO_LEFT_DATA GPIO_NUM_10
#define BOARD_AUDIO_RIGHT_DATA GPIO_NUM_3

#define BOARD_BOOT_BUTTON GPIO_NUM_9

// FreeRTOS stacks are board resources and are kept with the hardware profile.
// ESP-IDF stack sizes are expressed in bytes.
#define BOARD_TASK_STACK_DISPLAY 4096
#define BOARD_TASK_STACK_BOOT_BUTTON 4096
#define BOARD_TASK_STACK_SERVICES 6144
#define BOARD_TASK_STACK_RADIO_STREAM 6144
#define BOARD_TASK_STACK_AUDIO_DECODER 16384
#define BOARD_TASK_STACK_AUDIO_OUTPUT 4096
#define BOARD_TASK_STACK_WIFI_RSSI 2048
#define BOARD_TASK_STACK_WEBSOCKET_STATUS 8192
#define BOARD_TASK_STACK_WIFI_REBOOT 2048

