[CmdletBinding()]
param(
    [string]$FontPath = "C:\Windows\Fonts\CascadiaMono.ttf",
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"
$repository = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
if (-not $OutputPath) {
    $OutputPath = Join-Path $repository `
        "yoRadio\src\displays\fonts\C3Terminal12.h"
}
if (-not (Test-Path -LiteralPath $FontPath -PathType Leaf)) {
    throw "Cascadia Mono was not found at $FontPath"
}

Add-Type -AssemblyName System.Drawing
[Text.Encoding]::RegisterProvider([Text.CodePagesEncodingProvider]::Instance)
$cp437 = [Text.Encoding]::GetEncoding(437)

# Preserve yoRadio's control/icon characters. Text glyphs are freshly
# rasterized, while bytes 0x00..0x1f and 0x7f retain their existing meaning.
$legacySource = Get-Content -LiteralPath (Join-Path $repository `
    "yoRadio\fonts\glcdfont.c") -Raw
$legacy = [regex]::Matches($legacySource, '0x[0-9A-Fa-f]{2}') |
    ForEach-Object { [Convert]::ToByte($_.Value.Substring(2), 16) }
if ($legacy.Count -lt 1280) {
    throw "The existing 256-character 5x7 font could not be parsed"
}

$privateFonts = [System.Drawing.Text.PrivateFontCollection]::new()
$privateFonts.AddFontFile([IO.Path]::GetFullPath($FontPath))
$font = [System.Drawing.Font]::new(
    $privateFonts.Families[0], 11,
    [System.Drawing.FontStyle]::Regular,
    [System.Drawing.GraphicsUnit]::Pixel)
$format = [System.Drawing.StringFormat]::GenericTypographic
$format.FormatFlags = $format.FormatFlags -bor `
    [System.Drawing.StringFormatFlags]::NoClip

$cellWidth = 7
$cellHeight = 12
$pixels = New-Object 'bool[,]' $cellWidth, $cellHeight
$bitmapBytes = [Collections.Generic.List[byte]]::new()
$glyphLines = [Collections.Generic.List[string]]::new()

function Set-LegacyGlyph([int]$Code) {
    for ($y = 0; $y -lt $cellHeight; $y++) {
        $sourceY = [Math]::Min(6, [Math]::Floor($y * 7 / $cellHeight))
        for ($x = 0; $x -lt $cellWidth; $x++) {
            $sourceX = [Math]::Min(4, [Math]::Floor($x * 5 / $cellWidth))
            $column = $legacy[$Code * 5 + $sourceX]
            $pixels[$x, $y] = ($column -band (1 -shl $sourceY)) -ne 0
        }
    }
}

function Set-VectorGlyph([int]$Code) {
    $character = if ($Code -eq 0xA8) {
        [char]0x0401
    } elseif ($Code -eq 0xB8) {
        [char]0x0451
    } elseif ($Code -ge 0xC0) {
        [char](0x0410 + $Code - 0xC0)
    } else {
        $cp437.GetString([byte[]]@([byte]$Code))
    }

    $image = [System.Drawing.Bitmap]::new($cellWidth, $cellHeight)
    $graphics = [System.Drawing.Graphics]::FromImage($image)
    try {
        $graphics.Clear([System.Drawing.Color]::Black)
        $graphics.TextRenderingHint = `
            [System.Drawing.Text.TextRenderingHint]::SingleBitPerPixelGridFit
        $graphics.DrawString($character, $font, [System.Drawing.Brushes]::White,
            [System.Drawing.PointF]::new(0, -1), $format)
        for ($y = 0; $y -lt $cellHeight; $y++) {
            for ($x = 0; $x -lt $cellWidth; $x++) {
                $pixels[$x, $y] = $image.GetPixel($x, $y).R -ge 128
            }
        }
    } finally {
        $graphics.Dispose()
        $image.Dispose()
    }
}

function Set-ReplacementGlyph {
    for ($y = 0; $y -lt $cellHeight; $y++) {
        for ($x = 0; $x -lt $cellWidth; $x++) {
            $border = ($y -le 10) -and `
                ($x -eq 0 -or $x -eq 6 -or $y -eq 0 -or $y -eq 10)
            $question = ($y -eq 2 -and $x -ge 2 -and $x -le 4) -or `
                ($y -eq 3 -and $x -eq 4) -or `
                ($y -eq 4 -and $x -eq 3) -or `
                ($y -eq 5 -and $x -eq 3) -or `
                ($y -eq 7 -and $x -eq 3)
            $pixels[$x, $y] = $border -or $question
        }
    }
}

for ($code = 0; $code -le 255; $code++) {
    if ($code -eq 0x7F) {
        Set-ReplacementGlyph
    } elseif ($code -lt 0x20) {
        Set-LegacyGlyph $code
    } else {
        Set-VectorGlyph $code
    }

    $offset = $bitmapBytes.Count
    $packed = 0
    $mask = 0x80
    for ($y = 0; $y -lt $cellHeight; $y++) {
        for ($x = 0; $x -lt $cellWidth; $x++) {
            if ($pixels[$x, $y]) { $packed = $packed -bor $mask }
            $mask = $mask -shr 1
            if ($mask -eq 0) {
                $bitmapBytes.Add([byte]$packed)
                $packed = 0
                $mask = 0x80
            }
        }
    }
    if ($mask -ne 0x80) { $bitmapBytes.Add([byte]$packed) }
    $glyphLines.Add((
        "  {{ {0,5}, 7, 12, 7, 0, -10 }}, // 0x{1:X2}" -f $offset, $code))
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add("#ifndef C3_TERMINAL_12_H")
$lines.Add("#define C3_TERMINAL_12_H")
$lines.Add("")
$lines.Add("// Generated by tools/Generate-Esp32C3OledFont.ps1.")
$lines.Add("// Cascadia Mono is distributed by Microsoft under the SIL OFL 1.1:")
$lines.Add("// https://github.com/microsoft/cascadia-code/blob/main/LICENSE")
$lines.Add("// Fixed 7x12 cells cover the same 256 byte values as yoRadio's 5x7 font.")
$lines.Add("const uint8_t C3Terminal12Bitmaps[] PROGMEM = {")
for ($index = 0; $index -lt $bitmapBytes.Count; $index += 12) {
    $last = [Math]::Min($index + 11, $bitmapBytes.Count - 1)
    $chunk = for ($item = $index; $item -le $last; $item++) {
        '0x{0:X2}' -f $bitmapBytes[$item]
    }
    $lines.Add("  " + ($chunk -join ", ") + ",")
}
$lines.Add("};")
$lines.Add("")
$lines.Add("const GFXglyph C3Terminal12Glyphs[] PROGMEM = {")
foreach ($glyph in $glyphLines) { $lines.Add($glyph) }
$lines.Add("};")
$lines.Add("")
$lines.Add("const GFXfont C3Terminal12 PROGMEM = {")
$lines.Add("  (uint8_t *)C3Terminal12Bitmaps,")
$lines.Add("  (GFXglyph *)C3Terminal12Glyphs,")
$lines.Add("  0x00, 0xFF, 13")
$lines.Add("};")
$lines.Add("")
$lines.Add("#endif")

[IO.File]::WriteAllLines([IO.Path]::GetFullPath($OutputPath), $lines,
    [Text.UTF8Encoding]::new($false))
Write-Host "Generated $OutputPath ($($bitmapBytes.Count) bitmap bytes, 256 glyphs)"

$format.Dispose()
$font.Dispose()
$privateFonts.Dispose()
