# Frozen-layout quant_partition, saved GCC ASM; decoder-only ctx.encode=0.
# LX106 call0 ABI, original112-byte stack/callee saves and arithmetic.
# ROM L32R/CALLX0 pairs retained; no added RAM, no bitrate/mode limit.
# Only proven encoder branches/dead code removed; all audio branches kept.
# Generated by partition_frozen_proof.cjs; original C/GCC sources unchanged.
.section .text.patch0,"ax",@progbits
.begin no-transform
pc4024dafc:
addi a1, a1, -112 # original0x4024dafc
pc4024daff:
l32i.n a8, a2, 8 # original0x4024daff
pc4024db01:
l32i a9, a1, 112 # original0x4024db01
pc4024db04:
l32i.n a11, a8, 8 # original0x4024db04
pc4024db06:
s32i a12, a1, 104 # original0x4024db06
pc4024db09:
mov.n a12, a2 # original0x4024db09
pc4024db0b:
addi.n a2, a9, 1 # original0x4024db0b
pc4024db0d:
mull a2, a2, a11 # original0x4024db0d
pc4024db10:
l32i.n a10, a12, 12 # original0x4024db10
pc4024db12:
l32i a11, a8, 88 # original0x4024db12
pc4024db15:
add.n a2, a2, a10 # original0x4024db15
pc4024db17:
slli a2, a2, 1 # original0x4024db17
pc4024db1a:
add.n a2, a11, a2 # original0x4024db1a
pc4024db1c:
s32i a15, a1, 92 # original0x4024db1c
pc4024db1f:
l32i a11, a8, 92 # original0x4024db1f
pc4024db22:
l16si a2, a2, 0 # original0x4024db22
pc4024db25:
mov.n a15, a3 # original0x4024db25
pc4024db27:
s32i.n a7, a1, 24 # original0x4024db27
pc4024db29:
mov.n a3, a4 # original0x4024db29
pc4024db2b:
l16si a7, a1, 116 # original0x4024db2b
pc4024db2e:
l32i.n a4, a12, 28 # original0x4024db2e
pc4024db30:
s32i a13, a1, 100 # original0x4024db30
pc4024db33:
s32i a14, a1, 96 # original0x4024db33
pc4024db36:
s32i a0, a1, 108 # original0x4024db36
pc4024db39:
add.n a2, a11, a2 # original0x4024db39
pc4024db3b:
s32i.n a7, a1, 16 # original0x4024db3b
pc4024db3d:
s32i.n a4, a1, 20 # original0x4024db3d
pc4024db3f:
mov.n a14, a5 # original0x4024db3f
pc4024db41:
mov.n a13, a6 # original0x4024db41
pc4024db43:
l32i.n a7, a12, 0 # original0x4024db43
pc4024db45:
l32i.n a5, a12, 20 # original0x4024db45
pc4024db47:
l8ui a6, a2, 0 # original0x4024db47
pc4024db4a:
bnei a9, -1, pc4024db50 # original0x4024db4a
pc4024db4d:
j pc4024e1a6 # original0x4024db4d
pc4024db50:
add.n a4, a2, a6 # original0x4024db50
pc4024db52:
l8ui a4, a4, 0 # original0x4024db52
pc4024db55:
addi.n a4, a4, 12 # original0x4024db55
pc4024db57:
blt a4, a14, pc4024db5d # original0x4024db57
pc4024db5a:
j pc4024e1a6 # original0x4024db5a
pc4024db5d:
bgei a3, 3, pc4024db63 # original0x4024db5d
pc4024db60:
j pc4024e1a6 # original0x4024db60
pc4024db63:
srai a3, a3, 1 # original0x4024db63
pc4024db66:
slli a5, a3, 1 # original0x4024db66
pc4024db69:
add.n a2, a15, a5 # original0x4024db69
pc4024db6b:
addi.n a9, a9, -1 # original0x4024db6b
pc4024db6d:
s32i.n a3, a1, 36 # original0x4024db6d
pc4024db6f:
s32i.n a5, a1, 32 # original0x4024db6f
pc4024db71:
s32i a2, a1, 52 # original0x4024db71
pc4024db74:
s32i.n a9, a1, 44 # original0x4024db74
pc4024db76:
bnei a13, 1, pc4024db88 # original0x4024db76
pc4024db79:
l32i a4, a1, 120 # original0x4024db79
pc4024db7c:
extui a3, a4, 0, 1 # original0x4024db7c
pc4024db7f:
slli a2, a4, 1 # original0x4024db7f
pc4024db82:
or a2, a3, a2 # original0x4024db82
pc4024db85:
s32i a2, a1, 120 # original0x4024db85
pc4024db88:
l32i.n a2, a8, 48 # original0x4024db88
pc4024db8a:
slli a10, a10, 1 # original0x4024db8a
pc4024db8d:
add.n a10, a2, a10 # original0x4024db8d
pc4024db8f:
l32i.n a5, a1, 44 # original0x4024db8f
pc4024db91:
l16si a4, a10, 0 # original0x4024db91
pc4024db94:
slli a2, a5, 3 # original0x4024db94
pc4024db97:
add.n a4, a4, a2 # original0x4024db97
pc4024db99:
l32i.n a5, a1, 32 # original0x4024db99
pc4024db9b:
srai a2, a4, 1 # original0x4024db9b
pc4024db9e:
addi.n a3, a5, -1 # original0x4024db9e
pc4024dba0:
addi a2, a2, -4 # original0x4024dba0
pc4024dba3:
mull a2, a2, a3 # original0x4024dba3
pc4024dba6:
addi.n a5, a13, 1 # original0x4024dba6
pc4024dba8:
srai a5, a5, 1 # original0x4024dba8
pc4024dbab:
add a2, a2, a14 # original0x4024dbab
pc4024dbae:
s32i a4, a1, 64 # original0x4024dbae
pc4024dbb1:
s32i a7, a1, 68 # original0x4024dbb1
pc4024dbb4:
s32i.n a5, a1, 40 # original0x4024dbb4
pc4024dbb6:
l32r a0, fixed_40211970 # original0x4024dbb6
pc4024dbb9:
callx0 a0 # original0x4024dbb9
pc4024dbbc:
l32i a4, a1, 64 # original0x4024dbbc
pc4024dbbf:
addi a3, a14, -32 # original0x4024dbbf
pc4024dbc2:
sub a4, a3, a4 # original0x4024dbc2
pc4024dbc5:
l32i a7, a1, 68 # original0x4024dbc5
pc4024dbc8:
bge a4, a2, pc4024dbcd # original0x4024dbc8
pc4024dbcb:
mov.n a2, a4 # original0x4024dbcb
pc4024dbcd:
blti a2, 4, pc4024dbd3 # original0x4024dbcd
pc4024dbd0:
j pc4024dc61 # original0x4024dbd0
pc4024dbd3:
# proven encode=0 check removed: beqz a7, 4024dbd8 <quant_partition+220>
pc4024dbd5:
# unreachable encoder instruction: j 4024e3e8 <quant_partition+2284>
pc4024dbd8:
l32i.n a2, a1, 20 # original0x4024dbd8
pc4024dbda:
l32i.n a5, a2, 28 # original0x4024dbda
pc4024dbdc:
movi.n a4, 16 # original0x4024dbdc
pc4024dbde:
nsau a3, a5 # original0x4024dbde
pc4024dbe1:
sub a4, a4, a3 # original0x4024dbe1
pc4024dbe4:
l32i.n a2, a2, 20 # original0x4024dbe4
pc4024dbe6:
ssr a4 # original0x4024dbe6
pc4024dbe9:
srl a4, a5 # original0x4024dbe9
pc4024dbec:
srli a5, a4, 12 # original0x4024dbec
pc4024dbef:
addi a5, a5, -8 # original0x4024dbef
pc4024dbf2:
add.n a3, a3, a2 # original0x4024dbf2
pc4024dbf4:
l32r a2, fixed_402118a4 # original0x4024dbf4
pc4024dbf7:
slli a6, a5, 2 # original0x4024dbf7
pc4024dbfa:
add.n a2, a2, a6 # original0x4024dbfa
pc4024dbfc:
addi a3, a3, -32 # original0x4024dbfc
pc4024dbff:
l32i.n a6, a2, 0 # original0x4024dbff
pc4024dc01:
slli a3, a3, 3 # original0x4024dc01
pc4024dc04:
sub a3, a3, a5 # original0x4024dc04
pc4024dc07:
movi a2, 1 # original0x4024dc07
pc4024dc0a:
bltu a6, a4, pc4024dc10 # original0x4024dc0a
pc4024dc0d:
movi a2, 0 # original0x4024dc0d
pc4024dc10:
sub a2, a3, a2 # original0x4024dc10
pc4024dc13:
mov.n a11, a2 # original0x4024dc13
pc4024dc15:
l32i.n a2, a1, 20 # original0x4024dc15
pc4024dc17:
s32i a11, a1, 72 # original0x4024dc17
pc4024dc1a:
l32i.n a5, a2, 28 # original0x4024dc1a
pc4024dc1c:
movi.n a4, 16 # original0x4024dc1c
pc4024dc1e:
nsau a3, a5 # original0x4024dc1e
pc4024dc21:
sub a4, a4, a3 # original0x4024dc21
pc4024dc24:
l32i.n a2, a2, 20 # original0x4024dc24
pc4024dc26:
ssr a4 # original0x4024dc26
pc4024dc29:
srl a4, a5 # original0x4024dc29
pc4024dc2c:
srli a5, a4, 12 # original0x4024dc2c
pc4024dc2f:
addi a5, a5, -8 # original0x4024dc2f
pc4024dc32:
add.n a3, a3, a2 # original0x4024dc32
pc4024dc34:
l32r a2, fixed_402118a4 # original0x4024dc34
pc4024dc37:
slli a6, a5, 2 # original0x4024dc37
pc4024dc3a:
add.n a2, a2, a6 # original0x4024dc3a
pc4024dc3c:
addi a3, a3, -32 # original0x4024dc3c
pc4024dc3f:
l32i.n a6, a2, 0 # original0x4024dc3f
pc4024dc41:
slli a3, a3, 3 # original0x4024dc41
pc4024dc44:
sub a3, a3, a5 # original0x4024dc44
pc4024dc47:
movi a2, 1 # original0x4024dc47
pc4024dc4a:
bltu a6, a4, pc4024dc50 # original0x4024dc4a
pc4024dc4d:
movi a2, 0 # original0x4024dc4d
pc4024dc50:
sub a2, a3, a2 # original0x4024dc50
pc4024dc53:
l32i a11, a1, 72 # original0x4024dc53
pc4024dc56:
sub a11, a2, a11 # original0x4024dc56
pc4024dc59:
sub a10, a14, a11 # original0x4024dc59
pc4024dc5c:
j pc4024ded3 # original0x4024dc5c
pc4024dc61:
movi.n a3, 64 # original0x4024dc61
pc4024dc63:
bge a3, a2, pc4024dc68 # original0x4024dc63
pc4024dc66:
mov.n a2, a3 # original0x4024dc66
pc4024dc68:
extui a3, a2, 0, 3 # original0x4024dc68
pc4024dc6b:
slli a4, a3, 1 # original0x4024dc6b
pc4024dc6e:
l32r a3, fixed_40211a9c # original0x4024dc6e
pc4024dc71:
srai a2, a2, 3 # original0x4024dc71
pc4024dc74:
add.n a3, a3, a4 # original0x4024dc74
pc4024dc76:
l16si a3, a3, 0 # original0x4024dc76
pc4024dc79:
movi.n a4, 14 # original0x4024dc79
pc4024dc7b:
sub a2, a4, a2 # original0x4024dc7b
pc4024dc7e:
ssr a2 # original0x4024dc7e
pc4024dc81:
sra a2, a3 # original0x4024dc81
pc4024dc84:
addi.n a2, a2, 1 # original0x4024dc84
pc4024dc86:
movi.n a3, -2 # original0x4024dc86
pc4024dc88:
and a3, a2, a3 # original0x4024dc88
pc4024dc8b:
s32i.n a3, a1, 28 # original0x4024dc8b
pc4024dc8d:
j pc4024e36e # original0x4024dc8d
pc4024dc90:
# unreachable encoder instruction: j 4024e403 <quant_partition+2311>
pc4024dc95:
# unreachable encoder instruction: srai a2, a2, 31
pc4024dc98:
# unreachable encoder instruction: sub a2, a2, a7
pc4024dc9b:
# unreachable encoder instruction: slli a6, a7, 14
pc4024dc9e:
# unreachable encoder instruction: bgez a2, 4024e365 <quant_partition+2153>
pc4024dca1:
# unreachable encoder instruction: l32i a2, a1, 28
pc4024dca3:
# unreachable encoder instruction: blt a7, a2, 4024dca9 <quant_partition+429>
pc4024dca6:
# unreachable encoder instruction: j 4024e365 <quant_partition+2153>
pc4024dca9:
# unreachable encoder instruction: mov a3, a2
pc4024dcab:
# unreachable encoder instruction: mov a2, a6
pc4024dcad:
# unreachable encoder instruction: s32i a6, a1, 60
pc4024dcaf:
# unreachable encoder instruction: s32i a7, a1, 68
pc4024dcb2:
# unreachable encoder instruction: l32r a0, 40211924 <_stext+6420>
pc4024dcb5:
# unreachable encoder instruction: callx0 a0
pc4024dcb8:
# unreachable encoder instruction: slli a3, a2, 16
pc4024dcbb:
# unreachable encoder instruction: l32r a2, 40211aa0 <_stext+6800>
pc4024dcbe:
# unreachable encoder instruction: srai a3, a3, 16
pc4024dcc1:
# unreachable encoder instruction: sub a2, a2, a3
pc4024dcc4:
# unreachable encoder instruction: mul16s a2, a2, a2
pc4024dcc7:
# unreachable encoder instruction: mull a3, a3, a3
pc4024dcca:
# unreachable encoder instruction: addmi a2, a2, 4096
pc4024dccd:
# unreachable encoder instruction: slli a2, a2, 3
pc4024dcd0:
# unreachable encoder instruction: addmi a3, a3, 4096
pc4024dcd3:
# unreachable encoder instruction: srai a4, a2, 16
pc4024dcd6:
# unreachable encoder instruction: slli a3, a3, 3
pc4024dcd9:
# unreachable encoder instruction: movi a2, 4294966670
pc4024dcdc:
# unreachable encoder instruction: srai a5, a3, 16
pc4024dcdf:
# unreachable encoder instruction: mul16s a3, a2, a4
pc4024dce2:
# unreachable encoder instruction: mul16s a2, a2, a5
pc4024dce5:
# unreachable encoder instruction: l32r a8, 402118c4 <_stext+6324>
pc4024dce8:
# unreachable encoder instruction: addmi a3, a3, 16384
pc4024dceb:
# unreachable encoder instruction: addmi a2, a2, 16384
pc4024dcee:
# unreachable encoder instruction: srai a3, a3, 15
pc4024dcf1:
# unreachable encoder instruction: add a3, a3, a8
pc4024dcf3:
# unreachable encoder instruction: srai a2, a2, 15
pc4024dcf6:
# unreachable encoder instruction: add a2, a2, a8
pc4024dcf8:
# unreachable encoder instruction: mul16s a3, a3, a4
pc4024dcfb:
# unreachable encoder instruction: mul16s a2, a2, a5
pc4024dcfe:
# unreachable encoder instruction: l32r a8, 402118c8 <_stext+6328>
pc4024dd01:
# unreachable encoder instruction: addmi a3, a3, 16384
pc4024dd04:
# unreachable encoder instruction: addmi a2, a2, 16384
pc4024dd07:
# unreachable encoder instruction: srai a3, a3, 15
pc4024dd0a:
# unreachable encoder instruction: add a3, a3, a8
pc4024dd0c:
# unreachable encoder instruction: srai a2, a2, 15
pc4024dd0f:
# unreachable encoder instruction: add a2, a2, a8
pc4024dd11:
# unreachable encoder instruction: mul16s a3, a3, a4
pc4024dd14:
# unreachable encoder instruction: l32r a9, 40211a2c <_stext+6684>
pc4024dd17:
# unreachable encoder instruction: mul16s a2, a2, a5
pc4024dd1a:
# unreachable encoder instruction: addmi a3, a3, 16384
pc4024dd1d:
# unreachable encoder instruction: srai a8, a3, 15
pc4024dd20:
# unreachable encoder instruction: addmi a2, a2, 16384
pc4024dd23:
# unreachable encoder instruction: sub a3, a9, a4
pc4024dd26:
# unreachable encoder instruction: add a3, a8, a3
pc4024dd28:
# unreachable encoder instruction: sub a4, a9, a5
pc4024dd2b:
# unreachable encoder instruction: srai a2, a2, 15
pc4024dd2e:
# unreachable encoder instruction: add a2, a2, a4
pc4024dd30:
# unreachable encoder instruction: slli a3, a3, 16
pc4024dd33:
# unreachable encoder instruction: srai a3, a3, 16
pc4024dd36:
# unreachable encoder instruction: slli a2, a2, 16
pc4024dd39:
# unreachable encoder instruction: srai a4, a2, 16
pc4024dd3c:
# unreachable encoder instruction: nsau a9, a3
pc4024dd3f:
# unreachable encoder instruction: nsau a8, a4
pc4024dd42:
# unreachable encoder instruction: addi a2, a9, -17
pc4024dd45:
# unreachable encoder instruction: ssl a2
pc4024dd48:
# unreachable encoder instruction: sll a2, a3
pc4024dd4b:
# unreachable encoder instruction: addi a3, a8, -17
pc4024dd4e:
# unreachable encoder instruction: ssl a3
pc4024dd51:
# unreachable encoder instruction: sll a3, a4
pc4024dd54:
# unreachable encoder instruction: slli a2, a2, 16
pc4024dd57:
# unreachable encoder instruction: srai a4, a2, 16
pc4024dd5a:
# unreachable encoder instruction: l32r a10, 40211aa4 <_stext+6804>
pc4024dd5d:
# unreachable encoder instruction: slli a2, a3, 16
pc4024dd60:
# unreachable encoder instruction: srai a5, a2, 16
pc4024dd63:
# unreachable encoder instruction: mul16s a3, a5, a10
pc4024dd66:
# unreachable encoder instruction: mul16s a2, a4, a10
pc4024dd69:
# unreachable encoder instruction: addmi a3, a3, 16384
pc4024dd6c:
# unreachable encoder instruction: l32r a10, 40211aa8 <_stext+6808>
pc4024dd6f:
# unreachable encoder instruction: addmi a2, a2, 16384
pc4024dd72:
# unreachable encoder instruction: srai a2, a2, 15
pc4024dd75:
# unreachable encoder instruction: srai a3, a3, 15
pc4024dd78:
# unreachable encoder instruction: add a3, a3, a10
pc4024dd7a:
# unreachable encoder instruction: add a2, a2, a10
pc4024dd7c:
# unreachable encoder instruction: mul16s a5, a3, a5
pc4024dd7f:
# unreachable encoder instruction: mul16s a2, a2, a4
pc4024dd82:
# unreachable encoder instruction: sub a3, a8, a9
pc4024dd85:
# unreachable encoder instruction: slli a4, a3, 11
pc4024dd88:
# unreachable encoder instruction: addmi a2, a2, 16384
pc4024dd8b:
# unreachable encoder instruction: addmi a3, a5, 16384
pc4024dd8e:
# unreachable encoder instruction: l32i a5, a1, 36
pc4024dd90:
# unreachable encoder instruction: srai a2, a2, 15
pc4024dd93:
# unreachable encoder instruction: add a2, a2, a4
pc4024dd95:
# unreachable encoder instruction: srai a3, a3, 15
pc4024dd98:
# unreachable encoder instruction: addi a4, a5, -1
pc4024dd9a:
# unreachable encoder instruction: sub a2, a2, a3
pc4024dd9d:
# unreachable encoder instruction: slli a3, a4, 7
pc4024dda0:
# unreachable encoder instruction: mul16s a2, a2, a3
pc4024dda3:
# unreachable encoder instruction: l32i a6, a1, 60
pc4024dda5:
# unreachable encoder instruction: addmi a2, a2, 16384
pc4024dda8:
# unreachable encoder instruction: srai a2, a2, 15
pc4024ddab:
# unreachable encoder instruction: l32i a7, a1, 68
pc4024ddae:
# unreachable encoder instruction: bge a14, a2, 4024ddb4 <quant_partition+696>
pc4024ddb1:
# unreachable encoder instruction: j 4024e360 <quant_partition+2148>
pc4024ddb4:
# unreachable encoder instruction: neg a3, a14
pc4024ddb7:
# unreachable encoder instruction: blt a2, a3, 4024ddbd <quant_partition+705>
pc4024ddba:
# unreachable encoder instruction: j 4024e365 <quant_partition+2153>
pc4024ddbd:
# unreachable encoder instruction: movi a7, 0
pc4024ddbf:
# unreachable encoder instruction: mov a6, a7
pc4024ddc1:
# unreachable encoder instruction: j 4024e365 <quant_partition+2153>
pc4024ddc4:
# unreachable encoder instruction: l32i a2, a1, 28
pc4024ddc7:
# unreachable encoder instruction: or a3, a7, a7
pc4024ddca:
# unreachable encoder instruction: addi a4, a2, 1
pc4024ddcd:
# unreachable encoder instruction: l32i a2, a1, 20
pc4024ddcf:
# unreachable encoder instruction: s32i a6, a1, 60
pc4024ddd1:
# unreachable encoder instruction: call0 40253774 <ec_enc_uint>
pc4024ddd4:
# unreachable encoder instruction: l32i a6, a1, 60
pc4024ddd6:
# unreachable encoder instruction: j 4024de82 <quant_partition+902>
pc4024ddd9:
l32i a7, a1, 28 # original0x4024ddd9
pc4024dddc:
l32i a2, a1, 20 # original0x4024dddc
pc4024dddf:
addi a3, a7, 1 # original0x4024dddf
pc4024dde2:
call0 fixed_40246c20 # original0x4024dde2
pc4024dde5:
slli a6, a2, 14 # original0x4024dde5
pc4024dde8:
j pc4024de82 # original0x4024dde8
pc4024ddec:
# unreachable encoder instruction: l32i a3, a1, 28
pc4024ddee:
# unreachable encoder instruction: srai a2, a3, 1
pc4024ddf1:
# unreachable encoder instruction: addi a5, a2, 1
pc4024ddf3:
# unreachable encoder instruction: mull a5, a5, a5
pc4024ddf6:
# unreachable encoder instruction: blt a2, a7, 4024de04 <quant_partition+776>
pc4024ddf9:
# unreachable encoder instruction: addi a4, a7, 1
pc4024ddfb:
# unreachable encoder instruction: mull a3, a7, a4
pc4024ddfe:
# unreachable encoder instruction: srai a3, a3, 1
pc4024de01:
# unreachable encoder instruction: j 4024de16 <quant_partition+794>
pc4024de04:
# unreachable encoder instruction: sub a7, a3, a7
pc4024de07:
# unreachable encoder instruction: addi a4, a7, 1
pc4024de0a:
# unreachable encoder instruction: addi a3, a7, 2
pc4024de0d:
# unreachable encoder instruction: mull a3, a3, a4
pc4024de10:
# unreachable encoder instruction: srai a3, a3, 1
pc4024de13:
# unreachable encoder instruction: sub a3, a5, a3
pc4024de16:
# unreachable encoder instruction: l32i a2, a1, 20
pc4024de19:
# unreachable encoder instruction: add a4, a4, a3
pc4024de1b:
# unreachable encoder instruction: s32i a6, a1, 60
pc4024de1d:
# unreachable encoder instruction: call0 4025359c <ec_encode>
pc4024de20:
# unreachable encoder instruction: l32i a6, a1, 60
pc4024de22:
# unreachable encoder instruction: j 4024de82 <quant_partition+902>
pc4024de25:
slli a2, a2, 3 # original0x4024de25
pc4024de28:
addi a2, a2, 1 # original0x4024de28
pc4024de2b:
call0 fixed_40298598 # original0x4024de2b
pc4024de2e:
addi a2, a2, -1 # original0x4024de2e
pc4024de31:
srli a7, a2, 1 # original0x4024de31
pc4024de34:
addi a4, a7, 1 # original0x4024de34
pc4024de37:
mull a3, a7, a4 # original0x4024de37
pc4024de3a:
srai a3, a3, 1 # original0x4024de3a
pc4024de3d:
j pc4024de70 # original0x4024de3d
pc4024de40:
l32i.n a5, a1, 56 # original0x4024de40
pc4024de42:
addi.n a3, a5, -1 # original0x4024de42
pc4024de44:
sub a2, a3, a2 # original0x4024de44
pc4024de47:
slli a2, a2, 3 # original0x4024de47
pc4024de4a:
addi.n a2, a2, 1 # original0x4024de4a
pc4024de4c:
call0 fixed_40298598 # original0x4024de4c
pc4024de4f:
l32i.n a7, a1, 28 # original0x4024de4f
pc4024de51:
l32i.n a5, a1, 56 # original0x4024de51
pc4024de53:
addi.n a3, a7, 1 # original0x4024de53
pc4024de55:
slli a3, a3, 1 # original0x4024de55
pc4024de58:
sub a2, a3, a2 # original0x4024de58
pc4024de5b:
l32i.n a3, a1, 28 # original0x4024de5b
pc4024de5d:
srli a7, a2, 1 # original0x4024de5d
pc4024de60:
sub a2, a3, a7 # original0x4024de60
pc4024de63:
addi.n a4, a2, 1 # original0x4024de63
pc4024de65:
addi.n a3, a2, 2 # original0x4024de65
pc4024de67:
mull a3, a3, a4 # original0x4024de67
pc4024de6a:
srai a3, a3, 1 # original0x4024de6a
pc4024de6d:
sub a3, a5, a3 # original0x4024de6d
pc4024de70:
l32i.n a5, a1, 56 # original0x4024de70
pc4024de72:
l32i.n a2, a1, 20 # original0x4024de72
pc4024de74:
add.n a4, a3, a4 # original0x4024de74
pc4024de76:
s32i a7, a1, 68 # original0x4024de76
pc4024de79:
call0 fixed_402469dc # original0x4024de79
pc4024de7c:
l32i a7, a1, 68 # original0x4024de7c
pc4024de7f:
slli a6, a7, 14 # original0x4024de7f
pc4024de82:
l32i.n a3, a1, 28 # original0x4024de82
pc4024de84:
mov.n a2, a6 # original0x4024de84
pc4024de86:
l32r a0, fixed_40211924 # original0x4024de86
pc4024de89:
callx0 a0 # original0x4024de89
pc4024de8c:
s32i.n a2, a1, 28 # original0x4024de8c
pc4024de8e:
l32i.n a2, a1, 20 # original0x4024de8e
pc4024de90:
l32i.n a5, a2, 28 # original0x4024de90
pc4024de92:
movi.n a4, 16 # original0x4024de92
pc4024de94:
nsau a3, a5 # original0x4024de94
pc4024de97:
sub a4, a4, a3 # original0x4024de97
pc4024de9a:
l32i.n a2, a2, 20 # original0x4024de9a
pc4024de9c:
ssr a4 # original0x4024de9c
pc4024de9f:
srl a4, a5 # original0x4024de9f
pc4024dea2:
srli a5, a4, 12 # original0x4024dea2
pc4024dea5:
addi a5, a5, -8 # original0x4024dea5
pc4024dea8:
add.n a3, a3, a2 # original0x4024dea8
pc4024deaa:
l32r a2, fixed_402118a4 # original0x4024deaa
pc4024dead:
slli a6, a5, 2 # original0x4024dead
pc4024deb0:
add.n a2, a2, a6 # original0x4024deb0
pc4024deb2:
addi a3, a3, -32 # original0x4024deb2
pc4024deb5:
l32i.n a6, a2, 0 # original0x4024deb5
pc4024deb7:
slli a3, a3, 3 # original0x4024deb7
pc4024deba:
sub a3, a3, a5 # original0x4024deba
pc4024debd:
movi.n a2, 1 # original0x4024debd
pc4024debf:
bltu a6, a4, pc4024dec4 # original0x4024debf
pc4024dec2:
movi.n a2, 0 # original0x4024dec2
pc4024dec4:
sub a2, a3, a2 # original0x4024dec4
pc4024dec7:
l32i.n a7, a1, 48 # original0x4024dec7
pc4024dec9:
sub a11, a2, a7 # original0x4024dec9
pc4024decc:
l32i.n a2, a1, 28 # original0x4024decc
pc4024dece:
sub a10, a14, a11 # original0x4024dece
pc4024ded1:
bnez.n a2, pc4024df04 # original0x4024ded1
pc4024ded3:
l32i.n a7, a1, 16 # original0x4024ded3
pc4024ded5:
l32i.n a4, a1, 40 # original0x4024ded5
pc4024ded7:
slli a2, a7, 15 # original0x4024ded7
pc4024deda:
movi.n a3, 1 # original0x4024deda
pc4024dedc:
sub a2, a2, a7 # original0x4024dedc
pc4024dedf:
ssl a4 # original0x4024dedf
pc4024dee2:
sll a3, a3 # original0x4024dee2
pc4024dee5:
l32i a7, a1, 120 # original0x4024dee5
pc4024dee8:
addi.n a3, a3, -1 # original0x4024dee8
pc4024deea:
addmi a2, a2, 0x4000 # original0x4024deea
pc4024deed:
movi.n a5, 0 # original0x4024deed
pc4024deef:
srai a2, a2, 15 # original0x4024deef
pc4024def2:
and a7, a7, a3 # original0x4024def2
pc4024def5:
s32i.n a2, a1, 48 # original0x4024def5
pc4024def7:
s32i.n a5, a1, 20 # original0x4024def7
pc4024def9:
s32i a7, a1, 120 # original0x4024def9
pc4024defc:
s32i.n a5, a1, 28 # original0x4024defc
pc4024defe:
l32r a2, fixed_40211a98 # original0x4024defe
pc4024df01:
j pc4024e08c # original0x4024df01
pc4024df04:
mov.n a3, a2 # original0x4024df04
pc4024df06:
l32r a2, fixed_40211aa0 # original0x4024df06
pc4024df09:
bne a3, a2, pc4024df40 # original0x4024df09
pc4024df0c:
l32i.n a4, a1, 40 # original0x4024df0c
pc4024df0e:
l32i.n a7, a1, 16 # original0x4024df0e
pc4024df10:
movi.n a2, 1 # original0x4024df10
pc4024df12:
ssl a4 # original0x4024df12
pc4024df15:
sll a2, a2 # original0x4024df15
pc4024df18:
slli a3, a7, 15 # original0x4024df18
pc4024df1b:
addi.n a2, a2, -1 # original0x4024df1b
pc4024df1d:
ssl a4 # original0x4024df1d
pc4024df20:
sll a2, a2 # original0x4024df20
pc4024df23:
sub a3, a3, a7 # original0x4024df23
pc4024df26:
l32i a4, a1, 120 # original0x4024df26
pc4024df29:
addmi a3, a3, 0x4000 # original0x4024df29
pc4024df2c:
and a4, a4, a2 # original0x4024df2c
pc4024df2f:
srai a3, a3, 15 # original0x4024df2f
pc4024df32:
movi.n a5, 0 # original0x4024df32
pc4024df34:
s32i a4, a1, 120 # original0x4024df34
pc4024df37:
s32i.n a3, a1, 20 # original0x4024df37
pc4024df39:
l32i.n a2, a1, 28 # original0x4024df39
pc4024df3b:
s32i.n a5, a1, 48 # original0x4024df3b
pc4024df3d:
j pc4024e08c # original0x4024df3d
pc4024df40:
slli a3, a3, 16 # original0x4024df40
pc4024df43:
srai a3, a3, 16 # original0x4024df43
pc4024df46:
sub a2, a2, a3 # original0x4024df46
pc4024df49:
mul16s a2, a2, a2 # original0x4024df49
pc4024df4c:
mull a3, a3, a3 # original0x4024df4c
pc4024df4f:
addmi a2, a2, 0x1000 # original0x4024df4f
pc4024df52:
addmi a3, a3, 0x1000 # original0x4024df52
pc4024df55:
slli a2, a2, 3 # original0x4024df55
pc4024df58:
srai a2, a2, 16 # original0x4024df58
pc4024df5b:
movi a4, 0xfffffd8e # original0x4024df5b
pc4024df5e:
slli a3, a3, 3 # original0x4024df5e
pc4024df61:
srai a3, a3, 16 # original0x4024df61
pc4024df64:
mul16s a5, a4, a2 # original0x4024df64
pc4024df67:
mul16s a4, a4, a3 # original0x4024df67
pc4024df6a:
l32r a6, fixed_402118c4 # original0x4024df6a
pc4024df6d:
addmi a5, a5, 0x4000 # original0x4024df6d
pc4024df70:
addmi a4, a4, 0x4000 # original0x4024df70
pc4024df73:
srai a5, a5, 15 # original0x4024df73
pc4024df76:
add.n a5, a5, a6 # original0x4024df76
pc4024df78:
srai a4, a4, 15 # original0x4024df78
pc4024df7b:
add.n a4, a4, a6 # original0x4024df7b
pc4024df7d:
mul16s a5, a5, a2 # original0x4024df7d
pc4024df80:
mul16s a4, a4, a3 # original0x4024df80
pc4024df83:
l32r a6, fixed_402118c8 # original0x4024df83
pc4024df86:
addmi a5, a5, 0x4000 # original0x4024df86
pc4024df89:
addmi a4, a4, 0x4000 # original0x4024df89
pc4024df8c:
srai a5, a5, 15 # original0x4024df8c
pc4024df8f:
add.n a5, a5, a6 # original0x4024df8f
pc4024df91:
srai a4, a4, 15 # original0x4024df91
pc4024df94:
add.n a4, a4, a6 # original0x4024df94
pc4024df96:
mul16s a5, a5, a2 # original0x4024df96
pc4024df99:
l32r a7, fixed_40211a2c # original0x4024df99
pc4024df9c:
mul16s a4, a4, a3 # original0x4024df9c
pc4024df9f:
addmi a5, a5, 0x4000 # original0x4024df9f
pc4024dfa2:
sub a2, a7, a2 # original0x4024dfa2
pc4024dfa5:
srai a5, a5, 15 # original0x4024dfa5
pc4024dfa8:
addmi a4, a4, 0x4000 # original0x4024dfa8
pc4024dfab:
sub a7, a7, a3 # original0x4024dfab
pc4024dfae:
srai a4, a4, 15 # original0x4024dfae
pc4024dfb1:
add.n a3, a5, a2 # original0x4024dfb1
pc4024dfb3:
slli a3, a3, 16 # original0x4024dfb3
pc4024dfb6:
add.n a2, a4, a7 # original0x4024dfb6
pc4024dfb8:
srai a3, a3, 16 # original0x4024dfb8
pc4024dfbb:
slli a2, a2, 16 # original0x4024dfbb
pc4024dfbe:
srai a2, a2, 16 # original0x4024dfbe
pc4024dfc1:
nsau a9, a3 # original0x4024dfc1
pc4024dfc4:
nsau a8, a2 # original0x4024dfc4
pc4024dfc7:
addi a7, a9, -17 # original0x4024dfc7
pc4024dfca:
ssl a7 # original0x4024dfca
pc4024dfcd:
sll a7, a3 # original0x4024dfcd
pc4024dfd0:
addi a6, a8, -17 # original0x4024dfd0
pc4024dfd3:
ssl a6 # original0x4024dfd3
pc4024dfd6:
sll a6, a2 # original0x4024dfd6
pc4024dfd9:
l32r a5, fixed_40211aa4 # original0x4024dfd9
pc4024dfdc:
slli a7, a7, 16 # original0x4024dfdc
pc4024dfdf:
srai a7, a7, 16 # original0x4024dfdf
pc4024dfe2:
slli a6, a6, 16 # original0x4024dfe2
pc4024dfe5:
srai a6, a6, 16 # original0x4024dfe5
pc4024dfe8:
mov.n a4, a5 # original0x4024dfe8
pc4024dfea:
mul16s a5, a7, a5 # original0x4024dfea
pc4024dfed:
mul16s a4, a6, a4 # original0x4024dfed
pc4024dff0:
l32r a14, fixed_40211aa8 # original0x4024dff0
pc4024dff3:
addmi a5, a5, 0x4000 # original0x4024dff3
pc4024dff6:
srai a5, a5, 15 # original0x4024dff6
pc4024dff9:
addmi a4, a4, 0x4000 # original0x4024dff9
pc4024dffc:
add.n a5, a5, a14 # original0x4024dffc
pc4024dffe:
srai a4, a4, 15 # original0x4024dffe
pc4024e001:
mul16s a5, a5, a7 # original0x4024e001
pc4024e004:
add.n a4, a4, a14 # original0x4024e004
pc4024e006:
mul16s a4, a4, a6 # original0x4024e006
pc4024e009:
l32i.n a7, a1, 36 # original0x4024e009
pc4024e00b:
addmi a5, a5, 0x4000 # original0x4024e00b
pc4024e00e:
sub a8, a8, a9 # original0x4024e00e
pc4024e011:
addi.n a6, a7, -1 # original0x4024e011
pc4024e013:
srai a5, a5, 15 # original0x4024e013
pc4024e016:
l32i.n a7, a1, 16 # original0x4024e016
pc4024e018:
slli a8, a8, 11 # original0x4024e018
pc4024e01b:
addmi a4, a4, 0x4000 # original0x4024e01b
pc4024e01e:
srai a4, a4, 15 # original0x4024e01e
pc4024e021:
add.n a5, a5, a8 # original0x4024e021
pc4024e023:
sub a5, a5, a4 # original0x4024e023
pc4024e026:
mull a2, a2, a7 # original0x4024e026
pc4024e029:
mull a4, a3, a7 # original0x4024e029
pc4024e02c:
slli a6, a6, 7 # original0x4024e02c
pc4024e02f:
addmi a3, a2, 0x4000 # original0x4024e02f
pc4024e032:
addmi a4, a4, 0x4000 # original0x4024e032
pc4024e035:
mul16s a5, a5, a6 # original0x4024e035
pc4024e038:
slli a4, a4, 1 # original0x4024e038
pc4024e03b:
slli a3, a3, 1 # original0x4024e03b
pc4024e03e:
srai a4, a4, 16 # original0x4024e03e
pc4024e041:
srai a3, a3, 16 # original0x4024e041
pc4024e044:
addmi a2, a5, 0x4000 # original0x4024e044
pc4024e047:
s32i.n a4, a1, 20 # original0x4024e047
pc4024e049:
s32i.n a3, a1, 48 # original0x4024e049
pc4024e04b:
srai a2, a2, 15 # original0x4024e04b
pc4024e04e:
blti a13, 2, pc4024e08c # original0x4024e04e
pc4024e051:
l32i.n a4, a1, 28 # original0x4024e051
pc4024e053:
extui a3, a4, 0, 14 # original0x4024e053
pc4024e056:
beqz.n a3, pc4024e08c # original0x4024e056
pc4024e058:
l32r a3, fixed_40211788 # original0x4024e058
pc4024e05b:
bge a3, a4, pc4024e071 # original0x4024e05b
pc4024e05e:
l32i.n a5, a1, 44 # original0x4024e05e
pc4024e060:
movi.n a3, 4 # original0x4024e060
pc4024e062:
sub a3, a3, a5 # original0x4024e062
pc4024e065:
ssr a3 # original0x4024e065
pc4024e068:
sra a3, a2 # original0x4024e068
pc4024e06b:
sub a2, a2, a3 # original0x4024e06b
pc4024e06e:
j pc4024e08c # original0x4024e06e
pc4024e071:
l32i.n a7, a1, 36 # original0x4024e071
pc4024e073:
l32i.n a5, a1, 44 # original0x4024e073
pc4024e075:
movi.n a4, 5 # original0x4024e075
pc4024e077:
slli a3, a7, 3 # original0x4024e077
pc4024e07a:
sub a4, a4, a5 # original0x4024e07a
pc4024e07d:
ssr a4 # original0x4024e07d
pc4024e080:
sra a3, a3 # original0x4024e080
pc4024e083:
add a2, a2, a3 # original0x4024e083
pc4024e086:
blti a2, 1, pc4024e08c # original0x4024e086
pc4024e089:
movi a2, 0 # original0x4024e089
pc4024e08c:
sub a2, a10, a2 # original0x4024e08c
pc4024e08f:
extui a14, a2, 31, 1 # original0x4024e08f
pc4024e092:
add.n a14, a14, a2 # original0x4024e092
pc4024e094:
srai a14, a14, 1 # original0x4024e094
pc4024e097:
bge a10, a14, pc4024e09c # original0x4024e097
pc4024e09a:
mov.n a14, a10 # original0x4024e09a
pc4024e09c:
l32i.n a7, a12, 32 # original0x4024e09c
pc4024e09e:
l32i.n a4, a1, 24 # original0x4024e09e
pc4024e0a0:
sub a3, a7, a11 # original0x4024e0a0
pc4024e0a3:
s32i.n a7, a1, 16 # original0x4024e0a3
pc4024e0a5:
l32i.n a7, a1, 32 # original0x4024e0a5
pc4024e0a7:
movi.n a2, 0 # original0x4024e0a7
pc4024e0a9:
add.n a8, a4, a7 # original0x4024e0a9
pc4024e0ab:
movltz a14, a2, a14 # original0x4024e0ab
pc4024e0ae:
s32i.n a3, a12, 32 # original0x4024e0ae
pc4024e0b0:
moveqz a8, a2, a4 # original0x4024e0b0
pc4024e0b3:
l32i.n a3, a1, 40 # original0x4024e0b3
pc4024e0b5:
l32i a2, a1, 120 # original0x4024e0b5
pc4024e0b8:
sub a9, a10, a14 # original0x4024e0b8
pc4024e0bb:
ssr a3 # original0x4024e0bb
pc4024e0be:
sra a2, a2 # original0x4024e0be
pc4024e0c1:
s32i.n a2, a1, 32 # original0x4024e0c1
pc4024e0c3:
srai a13, a13, 1 # original0x4024e0c3
pc4024e0c6:
blt a14, a9, pc4024e13d # original0x4024e0c6
pc4024e0c9:
l32i a4, a1, 120 # original0x4024e0c9
pc4024e0cc:
l32i.n a7, a1, 44 # original0x4024e0cc
pc4024e0ce:
l32i.n a5, a1, 48 # original0x4024e0ce
pc4024e0d0:
s32i.n a4, a1, 8 # original0x4024e0d0
pc4024e0d2:
s32i.n a7, a1, 0 # original0x4024e0d2
pc4024e0d4:
l32i.n a4, a1, 36 # original0x4024e0d4
pc4024e0d6:
l32i.n a7, a1, 24 # original0x4024e0d6
pc4024e0d8:
s32i.n a5, a1, 4 # original0x4024e0d8
pc4024e0da:
mov.n a6, a3 # original0x4024e0da
pc4024e0dc:
mov.n a5, a14 # original0x4024e0dc
pc4024e0de:
mov.n a3, a15 # original0x4024e0de
pc4024e0e0:
mov.n a2, a12 # original0x4024e0e0
pc4024e0e2:
s32i.n a8, a1, 60 # original0x4024e0e2
pc4024e0e4:
s32i a9, a1, 68 # original0x4024e0e4
pc4024e0e7:
s32i a10, a1, 64 # original0x4024e0e7
pc4024e0ea:
s32i a11, a1, 72 # original0x4024e0ea
pc4024e0ed:
call0 fixed_4024dafc # original0x4024e0ed
pc4024e0f0:
mov.n a15, a2 # original0x4024e0f0
pc4024e0f2:
l32i.n a4, a1, 16 # original0x4024e0f2
pc4024e0f4:
l32i.n a2, a12, 32 # original0x4024e0f4
pc4024e0f6:
l32i a11, a1, 72 # original0x4024e0f6
pc4024e0f9:
sub a2, a2, a4 # original0x4024e0f9
pc4024e0fc:
add.n a2, a2, a11 # original0x4024e0fc
pc4024e0fe:
movi.n a3, 24 # original0x4024e0fe
pc4024e100:
add.n a14, a2, a14 # original0x4024e100
pc4024e102:
l32i.n a8, a1, 60 # original0x4024e102
pc4024e104:
l32i a9, a1, 68 # original0x4024e104
pc4024e107:
l32i a10, a1, 64 # original0x4024e107
pc4024e10a:
bge a3, a14, pc4024e116 # original0x4024e10a
pc4024e10d:
l32i.n a5, a1, 28 # original0x4024e10d
pc4024e10f:
beqz.n a5, pc4024e116 # original0x4024e10f
pc4024e111:
addi a9, a10, -24 # original0x4024e111
pc4024e114:
add.n a9, a9, a2 # original0x4024e114
pc4024e116:
l32i.n a3, a1, 44 # original0x4024e116
pc4024e118:
l32i.n a7, a1, 32 # original0x4024e118
pc4024e11a:
l32i.n a2, a1, 20 # original0x4024e11a
pc4024e11c:
s32i.n a3, a1, 0 # original0x4024e11c
pc4024e11e:
l32i.n a6, a1, 40 # original0x4024e11e
pc4024e120:
l32i.n a4, a1, 36 # original0x4024e120
pc4024e122:
l32i.n a3, a1, 52 # original0x4024e122
pc4024e124:
s32i.n a7, a1, 8 # original0x4024e124
pc4024e126:
s32i.n a2, a1, 4 # original0x4024e126
pc4024e128:
mov.n a7, a8 # original0x4024e128
pc4024e12a:
mov.n a5, a9 # original0x4024e12a
pc4024e12c:
mov.n a2, a12 # original0x4024e12c
pc4024e12e:
call0 fixed_4024dafc # original0x4024e12e
pc4024e131:
ssl a13 # original0x4024e131
pc4024e134:
sll a13, a2 # original0x4024e134
pc4024e137:
or a14, a13, a15 # original0x4024e137
pc4024e13a:
j pc4024e434 # original0x4024e13a
pc4024e13d:
l32i.n a5, a1, 20 # original0x4024e13d
pc4024e13f:
l32i.n a7, a1, 44 # original0x4024e13f
pc4024e141:
mov.n a6, a3 # original0x4024e141
pc4024e143:
l32i.n a4, a1, 36 # original0x4024e143
pc4024e145:
l32i.n a3, a1, 52 # original0x4024e145
pc4024e147:
s32i.n a2, a1, 8 # original0x4024e147
pc4024e149:
s32i.n a5, a1, 4 # original0x4024e149
pc4024e14b:
s32i.n a7, a1, 0 # original0x4024e14b
pc4024e14d:
mov.n a5, a9 # original0x4024e14d
pc4024e14f:
mov.n a7, a8 # original0x4024e14f
pc4024e151:
mov.n a2, a12 # original0x4024e151
pc4024e153:
s32i a9, a1, 68 # original0x4024e153
pc4024e156:
s32i a11, a1, 72 # original0x4024e156
pc4024e159:
call0 fixed_4024dafc # original0x4024e159
pc4024e15c:
l32i.n a3, a12, 32 # original0x4024e15c
pc4024e15e:
l32i.n a5, a1, 16 # original0x4024e15e
pc4024e160:
l32i a11, a1, 72 # original0x4024e160
pc4024e163:
sub a3, a3, a5 # original0x4024e163
pc4024e166:
l32i a9, a1, 68 # original0x4024e166
pc4024e169:
add.n a3, a3, a11 # original0x4024e169
pc4024e16b:
movi.n a4, 24 # original0x4024e16b
pc4024e16d:
add.n a9, a3, a9 # original0x4024e16d
pc4024e16f:
ssl a13 # original0x4024e16f
pc4024e172:
sll a13, a2 # original0x4024e172
pc4024e175:
bge a4, a9, pc4024e184 # original0x4024e175
pc4024e178:
l32i.n a7, a1, 28 # original0x4024e178
pc4024e17a:
addmi a2, a7, 0xffffc000 # original0x4024e17a
pc4024e17d:
beqz.n a2, pc4024e184 # original0x4024e17d
pc4024e17f:
addi a14, a14, -24 # original0x4024e17f
pc4024e182:
add.n a14, a9, a14 # original0x4024e182
pc4024e184:
l32i.n a4, a1, 44 # original0x4024e184
pc4024e186:
l32i a2, a1, 120 # original0x4024e186
pc4024e189:
l32i.n a3, a1, 48 # original0x4024e189
pc4024e18b:
s32i.n a4, a1, 0 # original0x4024e18b
pc4024e18d:
l32i.n a7, a1, 24 # original0x4024e18d
pc4024e18f:
l32i.n a6, a1, 40 # original0x4024e18f
pc4024e191:
l32i.n a4, a1, 36 # original0x4024e191
pc4024e193:
s32i.n a2, a1, 8 # original0x4024e193
pc4024e195:
s32i.n a3, a1, 4 # original0x4024e195
pc4024e197:
mov.n a5, a14 # original0x4024e197
pc4024e199:
mov.n a3, a15 # original0x4024e199
pc4024e19b:
mov.n a2, a12 # original0x4024e19b
pc4024e19d:
call0 fixed_4024dafc # original0x4024e19d
pc4024e1a0:
or a14, a13, a2 # original0x4024e1a0
pc4024e1a3:
j pc4024e434 # original0x4024e1a3
pc4024e1a6:
addi.n a9, a6, 1 # original0x4024e1a6
pc4024e1a8:
srai a9, a9, 1 # original0x4024e1a8
pc4024e1ab:
add.n a4, a2, a9 # original0x4024e1ab
pc4024e1ad:
l8ui a4, a4, 0 # original0x4024e1ad
pc4024e1b0:
addi.n a8, a14, -1 # original0x4024e1b0
pc4024e1b2:
blt a4, a8, pc4024e1ba # original0x4024e1b2
pc4024e1b5:
mov.n a6, a9 # original0x4024e1b5
pc4024e1b7:
movi a9, 0 # original0x4024e1b7
pc4024e1ba:
add.n a4, a9, a6 # original0x4024e1ba
pc4024e1bc:
addi.n a4, a4, 1 # original0x4024e1bc
pc4024e1be:
srai a4, a4, 1 # original0x4024e1be
pc4024e1c1:
add.n a10, a2, a4 # original0x4024e1c1
pc4024e1c3:
l8ui a10, a10, 0 # original0x4024e1c3
pc4024e1c6:
blt a10, a8, pc4024e1cd # original0x4024e1c6
pc4024e1c9:
mov.n a6, a4 # original0x4024e1c9
pc4024e1cb:
mov.n a4, a9 # original0x4024e1cb
pc4024e1cd:
add.n a9, a4, a6 # original0x4024e1cd
pc4024e1cf:
addi.n a9, a9, 1 # original0x4024e1cf
pc4024e1d1:
srai a9, a9, 1 # original0x4024e1d1
pc4024e1d4:
add.n a10, a2, a9 # original0x4024e1d4
pc4024e1d6:
l8ui a10, a10, 0 # original0x4024e1d6
pc4024e1d9:
blt a10, a8, pc4024e1e1 # original0x4024e1d9
pc4024e1dc:
mov.n a6, a9 # original0x4024e1dc
pc4024e1de:
or a9, a4, a4 # original0x4024e1de
pc4024e1e1:
add.n a4, a6, a9 # original0x4024e1e1
pc4024e1e3:
addi.n a4, a4, 1 # original0x4024e1e3
pc4024e1e5:
srai a4, a4, 1 # original0x4024e1e5
pc4024e1e8:
add.n a10, a2, a4 # original0x4024e1e8
pc4024e1ea:
l8ui a10, a10, 0 # original0x4024e1ea
pc4024e1ed:
blt a10, a8, pc4024e1f5 # original0x4024e1ed
pc4024e1f0:
mov.n a6, a4 # original0x4024e1f0
pc4024e1f2:
or a4, a9, a9 # original0x4024e1f2
pc4024e1f5:
add.n a9, a6, a4 # original0x4024e1f5
pc4024e1f7:
addi.n a9, a9, 1 # original0x4024e1f7
pc4024e1f9:
srai a9, a9, 1 # original0x4024e1f9
pc4024e1fc:
add.n a10, a2, a9 # original0x4024e1fc
pc4024e1fe:
l8ui a10, a10, 0 # original0x4024e1fe
pc4024e201:
blt a10, a8, pc4024e209 # original0x4024e201
pc4024e204:
mov.n a6, a9 # original0x4024e204
pc4024e206:
or a9, a4, a4 # original0x4024e206
pc4024e209:
add.n a4, a6, a9 # original0x4024e209
pc4024e20b:
addi.n a4, a4, 1 # original0x4024e20b
pc4024e20d:
srai a4, a4, 1 # original0x4024e20d
pc4024e210:
add.n a10, a2, a4 # original0x4024e210
pc4024e212:
l8ui a10, a10, 0 # original0x4024e212
pc4024e215:
blt a10, a8, pc4024e21d # original0x4024e215
pc4024e218:
mov.n a6, a4 # original0x4024e218
pc4024e21a:
or a4, a9, a9 # original0x4024e21a
pc4024e21d:
add.n a9, a2, a6 # original0x4024e21d
pc4024e21f:
l8ui a9, a9, 0 # original0x4024e21f
pc4024e222:
sub a9, a9, a8 # original0x4024e222
pc4024e225:
beqz a4, pc4024e3b0 # original0x4024e225
pc4024e228:
add.n a10, a2, a4 # original0x4024e228
pc4024e22a:
l8ui a11, a10, 0 # original0x4024e22a
pc4024e22d:
mov.n a10, a4 # original0x4024e22d
pc4024e22f:
sub a8, a8, a11 # original0x4024e22f
pc4024e232:
bge a9, a8, pc4024e23c # original0x4024e232
pc4024e235:
beqz a6, pc4024e2aa # original0x4024e235
pc4024e238:
mov.n a10, a6 # original0x4024e238
pc4024e23a:
mov.n a4, a6 # original0x4024e23a
pc4024e23c:
add.n a10, a2, a10 # original0x4024e23c
pc4024e23e:
l8ui a8, a10, 0 # original0x4024e23e
pc4024e241:
l32i.n a6, a12, 32 # original0x4024e241
pc4024e243:
addi.n a8, a8, 1 # original0x4024e243
pc4024e245:
sub a6, a6, a8 # original0x4024e245
pc4024e248:
s32i.n a6, a12, 32 # original0x4024e248
pc4024e24a:
bgez a6, pc4024e265 # original0x4024e24a
pc4024e24d:
add.n a6, a6, a8 # original0x4024e24d
pc4024e24f:
addi.n a4, a4, -1 # original0x4024e24f
pc4024e251:
s32i.n a6, a12, 32 # original0x4024e251
pc4024e253:
add.n a8, a2, a4 # original0x4024e253
pc4024e255:
beqz a4, pc4024e2aa # original0x4024e255
pc4024e258:
l8ui a8, a8, 0 # original0x4024e258
pc4024e25b:
addi.n a8, a8, 1 # original0x4024e25b
pc4024e25d:
sub a6, a6, a8 # original0x4024e25d
pc4024e260:
s32i.n a6, a12, 32 # original0x4024e260
pc4024e262:
bltz a6, pc4024e24d # original0x4024e262
pc4024e265:
blti a4, 8, pc4024e278 # original0x4024e265
pc4024e268:
extui a2, a4, 0, 3 # original0x4024e268
pc4024e26b:
srai a4, a4, 3 # original0x4024e26b
pc4024e26e:
addi.n a2, a2, 8 # original0x4024e26e
pc4024e270:
addi.n a4, a4, -1 # original0x4024e270
pc4024e272:
ssl a4 # original0x4024e272
pc4024e275:
sll a4, a2 # original0x4024e275
pc4024e278:
# proven encode=0 check removed: beqz a7, 4024e297 <quant_partition+1947>
pc4024e27b:
# unreachable encoder instruction: l32i a7, a1, 16
pc4024e27e:
# unreachable encoder instruction: l32i a6, a12, 44
pc4024e281:
# unreachable encoder instruction: l32i a2, a12, 4
pc4024e283:
# unreachable encoder instruction: s32i a7, a1, 0
pc4024e285:
# unreachable encoder instruction: l32i a7, a1, 20
pc4024e287:
# unreachable encoder instruction: s32i a6, a1, 8
pc4024e289:
# unreachable encoder instruction: s32i a2, a1, 4
pc4024e28b:
# unreachable encoder instruction: mov a6, a13
pc4024e28d:
# unreachable encoder instruction: mov a2, a15
pc4024e28f:
# unreachable encoder instruction: call0 40248cb4 <alg_quant>
pc4024e292:
# unreachable encoder instruction: mov a14, a2
pc4024e294:
# unreachable encoder instruction: j 4024e434 <quant_partition+2360>
pc4024e297:
l32i.n a7, a1, 16 # original0x4024e297
pc4024e299:
mov.n a6, a13 # original0x4024e299
pc4024e29b:
s32i.n a7, a1, 0 # original0x4024e29b
pc4024e29d:
l32i.n a7, a1, 20 # original0x4024e29d
pc4024e29f:
mov.n a2, a15 # original0x4024e29f
pc4024e2a1:
call0 fixed_402493b0 # original0x4024e2a1
pc4024e2a4:
mov.n a14, a2 # original0x4024e2a4
pc4024e2a6:
j pc4024e434 # original0x4024e2a6
pc4024e2aa:
l32i a2, a12, 4 # original0x4024e2aa
pc4024e2ad:
movi a14, 0 # original0x4024e2ad
pc4024e2b0:
bne a2, a14, pc4024e2b6 # original0x4024e2b0
pc4024e2b3:
j pc4024e434 # original0x4024e2b3
pc4024e2b6:
movi a2, 1 # original0x4024e2b6
pc4024e2b9:
ssl a13 # original0x4024e2b9
pc4024e2bc:
sll a13, a2 # original0x4024e2bc
pc4024e2bf:
l32i a2, a1, 120 # original0x4024e2bf
pc4024e2c2:
addi.n a13, a13, -1 # original0x4024e2c2
pc4024e2c4:
and a14, a2, a13 # original0x4024e2c4
pc4024e2c7:
bnez.n a14, pc4024e2d4 # original0x4024e2c7
pc4024e2c9:
movi.n a4, 2 # original0x4024e2c9
pc4024e2cb:
mov.n a2, a15 # original0x4024e2cb
pc4024e2cd:
call0 fixed_40242a14 # original0x4024e2cd
pc4024e2d0:
j pc4024e434 # original0x4024e2d0
pc4024e2d4:
l32i.n a4, a1, 24 # original0x4024e2d4
pc4024e2d6:
beqz.n a4, pc4024e2e0 # original0x4024e2d6
pc4024e2d8:
bgei a3, 1, pc4024e308 # original0x4024e2d8
pc4024e2db:
j pc4024e351 # original0x4024e2db
pc4024e2e0:
blti a3, 1, pc4024e34e # original0x4024e2e0
pc4024e2e3:
slli a6, a3, 1 # original0x4024e2e3
pc4024e2e6:
l32i.n a2, a12, 40 # original0x4024e2e6
pc4024e2e8:
l32r a8, fixed_40211740 # original0x4024e2e8
pc4024e2eb:
l32r a7, fixed_40211744 # original0x4024e2eb
pc4024e2ee:
or a4, a15, a15 # original0x4024e2ee
pc4024e2f1:
add a6, a6, a15 # original0x4024e2f1
pc4024e2f4:
mull a2, a2, a8 # original0x4024e2f4
pc4024e2f7:
add.n a2, a2, a7 # original0x4024e2f7
pc4024e2f9:
srai a5, a2, 20 # original0x4024e2f9
pc4024e2fc:
s16i a5, a4, 0 # original0x4024e2fc
pc4024e2ff:
addi.n a4, a4, 2 # original0x4024e2ff
pc4024e301:
bne a6, a4, pc4024e2f4 # original0x4024e301
pc4024e304:
j pc4024e347 # original0x4024e304
pc4024e308:
slli a9, a3, 1 # original0x4024e308
pc4024e30b:
l32i.n a2, a12, 40 # original0x4024e30b
pc4024e30d:
l32r a8, fixed_40211740 # original0x4024e30d
pc4024e310:
l32r a7, fixed_40211744 # original0x4024e310
pc4024e313:
l32r a10, fixed_40211aac # original0x4024e313
pc4024e316:
or a5, a15, a15 # original0x4024e316
pc4024e319:
add a9, a4, a9 # original0x4024e319
pc4024e31c:
mull a2, a2, a8 # original0x4024e31c
pc4024e31f:
l16ui a6, a4, 0 # original0x4024e31f
pc4024e322:
add.n a2, a2, a7 # original0x4024e322
pc4024e324:
addi.n a4, a4, 2 # original0x4024e324
pc4024e326:
bany a2, a10, pc4024e338 # original0x4024e326
pc4024e329:
addi a6, a6, -4 # original0x4024e329
pc4024e32c:
s16i a6, a5, 0 # original0x4024e32c
pc4024e32f:
addi.n a5, a5, 2 # original0x4024e32f
pc4024e331:
bne a4, a9, pc4024e31c # original0x4024e331
pc4024e334:
j pc4024e342 # original0x4024e334
pc4024e338:
addi.n a6, a6, 4 # original0x4024e338
pc4024e33a:
s16i a6, a5, 0 # original0x4024e33a
pc4024e33d:
addi.n a5, a5, 2 # original0x4024e33d
pc4024e33f:
bne a4, a9, pc4024e31c # original0x4024e33f
pc4024e342:
s32i.n a2, a12, 40 # original0x4024e342
pc4024e344:
j pc4024e351 # original0x4024e344
pc4024e347:
s32i.n a2, a12, 40 # original0x4024e347
pc4024e349:
mov.n a14, a13 # original0x4024e349
pc4024e34b:
j pc4024e351 # original0x4024e34b
pc4024e34e:
or a14, a13, a13 # original0x4024e34e
pc4024e351:
l32i a5, a12, 44 # original0x4024e351
pc4024e354:
l32i a4, a1, 16 # original0x4024e354
pc4024e357:
mov.n a2, a15 # original0x4024e357
pc4024e359:
call0 fixed_402496bc # original0x4024e359
pc4024e35c:
j pc4024e434 # original0x4024e35c
pc4024e360:
# unreachable encoder instruction: l32i a7, a1, 28
pc4024e362:
# unreachable encoder instruction: slli a6, a7, 14
pc4024e365:
# unreachable encoder instruction: bgei a13, 2, 4024e36b <quant_partition+2159>
pc4024e368:
# unreachable encoder instruction: j 4024ddec <quant_partition+752>
pc4024e36b:
# unreachable encoder instruction: j 4024ddc4 <quant_partition+712>
pc4024e36e:
l32i.n a2, a1, 20 # original0x4024e36e
pc4024e370:
l32i.n a5, a2, 28 # original0x4024e370
pc4024e372:
movi.n a4, 16 # original0x4024e372
pc4024e374:
nsau a3, a5 # original0x4024e374
pc4024e377:
sub a4, a4, a3 # original0x4024e377
pc4024e37a:
l32i.n a2, a2, 20 # original0x4024e37a
pc4024e37c:
ssr a4 # original0x4024e37c
pc4024e37f:
srl a4, a5 # original0x4024e37f
pc4024e382:
srli a5, a4, 12 # original0x4024e382
pc4024e385:
addi a5, a5, -8 # original0x4024e385
pc4024e388:
add.n a3, a3, a2 # original0x4024e388
pc4024e38a:
l32r a2, fixed_402118a4 # original0x4024e38a
pc4024e38d:
slli a6, a5, 2 # original0x4024e38d
pc4024e390:
add.n a2, a2, a6 # original0x4024e390
pc4024e392:
addi a3, a3, -32 # original0x4024e392
pc4024e395:
l32i.n a6, a2, 0 # original0x4024e395
pc4024e397:
slli a3, a3, 3 # original0x4024e397
pc4024e39a:
sub a3, a3, a5 # original0x4024e39a
pc4024e39d:
movi.n a2, 1 # original0x4024e39d
pc4024e39f:
bltu a6, a4, pc4024e3a4 # original0x4024e39f
pc4024e3a2:
movi.n a2, 0 # original0x4024e3a2
pc4024e3a4:
sub a2, a3, a2 # original0x4024e3a4
pc4024e3a7:
s32i.n a2, a1, 48 # original0x4024e3a7
pc4024e3a9:
blti a13, 2, pc4024e3b9 # original0x4024e3a9
pc4024e3ac:
j pc4024ddd9 # original0x4024e3ac
pc4024e3b0:
blt a9, a14, pc4024e3b6 # original0x4024e3b0
pc4024e3b3:
j pc4024e2aa # original0x4024e3b3
pc4024e3b6:
j pc4024e235 # original0x4024e3b6
pc4024e3b9:
l32i a7, a1, 28 # original0x4024e3b9
pc4024e3bc:
l32i a2, a1, 20 # original0x4024e3bc
pc4024e3bf:
srai a5, a7, 1 # original0x4024e3bf
pc4024e3c2:
addi a4, a5, 1 # original0x4024e3c2
pc4024e3c5:
mull a7, a4, a4 # original0x4024e3c5
pc4024e3c8:
s32i a4, a1, 64 # original0x4024e3c8
pc4024e3cb:
mov.n a3, a7 # original0x4024e3cb
pc4024e3cd:
s32i.n a5, a1, 60 # original0x4024e3cd
pc4024e3cf:
s32i.n a7, a1, 56 # original0x4024e3cf
pc4024e3d1:
call0 fixed_4024695c # original0x4024e3d1
pc4024e3d4:
l32i a4, a1, 64 # original0x4024e3d4
pc4024e3d7:
l32i.n a5, a1, 60 # original0x4024e3d7
pc4024e3d9:
mull a3, a4, a5 # original0x4024e3d9
pc4024e3dc:
srai a3, a3, 1 # original0x4024e3dc
pc4024e3df:
bge a2, a3, pc4024e3e5 # original0x4024e3df
pc4024e3e2:
j pc4024de25 # original0x4024e3e2
pc4024e3e5:
j pc4024de40 # original0x4024e3e5
pc4024e3e8:
# unreachable encoder instruction: l32i a6, a12, 44
pc4024e3eb:
# unreachable encoder instruction: l32i a5, a1, 36
pc4024e3ee:
# unreachable encoder instruction: l32i a3, a1, 52
pc4024e3f0:
# unreachable encoder instruction: movi a4, 0
pc4024e3f2:
# unreachable encoder instruction: mov a2, a15
pc4024e3f4:
# unreachable encoder instruction: call0 40249774 <stereo_itheta>
pc4024e3f7:
# unreachable encoder instruction: s32i a2, a1, 28
pc4024e3f9:
# unreachable encoder instruction: l32i a2, a1, 20
pc4024e3fb:
# unreachable encoder instruction: call0 40246830 <ec_tell_frac>
pc4024e3fe:
# unreachable encoder instruction: s32i a2, a1, 48
pc4024e400:
# unreachable encoder instruction: j 4024de8e <quant_partition+914>
pc4024e403:
# unreachable encoder instruction: l32i a6, a12, 44
pc4024e406:
# unreachable encoder instruction: l32i a5, a1, 36
pc4024e409:
# unreachable encoder instruction: l32i a3, a1, 52
pc4024e40b:
# unreachable encoder instruction: movi a4, 0
pc4024e40d:
# unreachable encoder instruction: or a2, a15, a15
pc4024e410:
# unreachable encoder instruction: call0 40249774 <stereo_itheta>
pc4024e413:
# unreachable encoder instruction: mov a3, a2
pc4024e415:
# unreachable encoder instruction: l32i a2, a1, 20
pc4024e417:
# unreachable encoder instruction: s32i a3, a1, 60
pc4024e419:
# unreachable encoder instruction: call0 40246830 <ec_tell_frac>
pc4024e41c:
# unreachable encoder instruction: l32i a3, a1, 60
pc4024e41e:
# unreachable encoder instruction: l32i a7, a1, 28
pc4024e420:
# unreachable encoder instruction: s32i a2, a1, 48
pc4024e422:
# unreachable encoder instruction: mull a2, a3, a7
pc4024e425:
# unreachable encoder instruction: l32i a3, a12, 56
pc4024e427:
# unreachable encoder instruction: addmi a2, a2, 8192
pc4024e42a:
# unreachable encoder instruction: srai a7, a2, 14
pc4024e42d:
# unreachable encoder instruction: bnez a3, 4024dc95 <quant_partition+409>
pc4024e430:
# unreachable encoder instruction: j 4024e362 <quant_partition+2150>
pc4024e434:
l32i a0, a1, 108 # original0x4024e434
pc4024e437:
mov.n a2, a14 # original0x4024e437
pc4024e439:
l32i a12, a1, 104 # original0x4024e439
pc4024e43c:
l32i a13, a1, 100 # original0x4024e43c
pc4024e43f:
l32i a14, a1, 96 # original0x4024e43f
pc4024e442:
l32i a15, a1, 92 # original0x4024e442
pc4024e445:
addi a1, a1, 112 # original0x4024e445
pc4024e448:
ret.n  # original0x4024e448
frozen_live_end:
.space 2382 - (. - pc4024dafc), 0
.end no-transform
